// automatically generated by the FlatBuffers compiler, do not modify

package com.automq.elasticstream.client.flatc.header;

@SuppressWarnings("unused")
public final class ClientRole {
  private ClientRole() { }
  public static final byte CLIENT_ROLE_UNSPECIFIED = 0;
  public static final byte CLIENT_ROLE_PM = 1;
  public static final byte CLIENT_ROLE_DATA_NODE = 2;
  public static final byte CLIENT_ROLE_CUSTOMER = 3;

  public static final String[] names = { "CLIENT_ROLE_UNSPECIFIED", "CLIENT_ROLE_PM", "CLIENT_ROLE_DATA_NODE", "CLIENT_ROLE_CUSTOMER", };

  public static String name(int e) { return names[e]; }
}

