// automatically generated by the FlatBuffers compiler, do not modify

package com.automq.elasticstream.client.flatc.header;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DescribeStreamRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static DescribeStreamRequest getRootAsDescribeStreamRequest(ByteBuffer _bb) { return getRootAsDescribeStreamRequest(_bb, new DescribeStreamRequest()); }
  public static DescribeStreamRequest getRootAsDescribeStreamRequest(ByteBuffer _bb, DescribeStreamRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DescribeStreamRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int timeoutMs() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long streamId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createDescribeStreamRequest(FlatBufferBuilder builder,
      int timeoutMs,
      long streamId) {
    builder.startTable(2);
    DescribeStreamRequest.addStreamId(builder, streamId);
    DescribeStreamRequest.addTimeoutMs(builder, timeoutMs);
    return DescribeStreamRequest.endDescribeStreamRequest(builder);
  }

  public static void startDescribeStreamRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addTimeoutMs(FlatBufferBuilder builder, int timeoutMs) { builder.addInt(0, timeoutMs, 0); }
  public static void addStreamId(FlatBufferBuilder builder, long streamId) { builder.addLong(1, streamId, 0L); }
  public static int endDescribeStreamRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DescribeStreamRequest get(int j) { return get(new DescribeStreamRequest(), j); }
    public DescribeStreamRequest get(DescribeStreamRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public DescribeStreamRequestT unpack() {
    DescribeStreamRequestT _o = new DescribeStreamRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(DescribeStreamRequestT _o) {
    int _oTimeoutMs = timeoutMs();
    _o.setTimeoutMs(_oTimeoutMs);
    long _oStreamId = streamId();
    _o.setStreamId(_oStreamId);
  }
  public static int pack(FlatBufferBuilder builder, DescribeStreamRequestT _o) {
    if (_o == null) return 0;
    return createDescribeStreamRequest(
      builder,
      _o.getTimeoutMs(),
      _o.getStreamId());
  }
}

