// automatically generated by the FlatBuffers compiler, do not modify

package com.automq.elasticstream.client.flatc.header;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DescribeStreamResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static DescribeStreamResponse getRootAsDescribeStreamResponse(ByteBuffer _bb) { return getRootAsDescribeStreamResponse(_bb, new DescribeStreamResponse()); }
  public static DescribeStreamResponse getRootAsDescribeStreamResponse(ByteBuffer _bb, DescribeStreamResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DescribeStreamResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.automq.elasticstream.client.flatc.header.Status status() { return status(new com.automq.elasticstream.client.flatc.header.Status()); }
  public com.automq.elasticstream.client.flatc.header.Status status(com.automq.elasticstream.client.flatc.header.Status obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public int throttleTimeMs() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public com.automq.elasticstream.client.flatc.header.Stream stream() { return stream(new com.automq.elasticstream.client.flatc.header.Stream()); }
  public com.automq.elasticstream.client.flatc.header.Stream stream(com.automq.elasticstream.client.flatc.header.Stream obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createDescribeStreamResponse(FlatBufferBuilder builder,
      int statusOffset,
      int throttleTimeMs,
      int streamOffset) {
    builder.startTable(3);
    DescribeStreamResponse.addStream(builder, streamOffset);
    DescribeStreamResponse.addThrottleTimeMs(builder, throttleTimeMs);
    DescribeStreamResponse.addStatus(builder, statusOffset);
    return DescribeStreamResponse.endDescribeStreamResponse(builder);
  }

  public static void startDescribeStreamResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addStatus(FlatBufferBuilder builder, int statusOffset) { builder.addOffset(0, statusOffset, 0); }
  public static void addThrottleTimeMs(FlatBufferBuilder builder, int throttleTimeMs) { builder.addInt(1, throttleTimeMs, 0); }
  public static void addStream(FlatBufferBuilder builder, int streamOffset) { builder.addOffset(2, streamOffset, 0); }
  public static int endDescribeStreamResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // status
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DescribeStreamResponse get(int j) { return get(new DescribeStreamResponse(), j); }
    public DescribeStreamResponse get(DescribeStreamResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public DescribeStreamResponseT unpack() {
    DescribeStreamResponseT _o = new DescribeStreamResponseT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(DescribeStreamResponseT _o) {
    if (status() != null) _o.setStatus(status().unpack());
    else _o.setStatus(null);
    int _oThrottleTimeMs = throttleTimeMs();
    _o.setThrottleTimeMs(_oThrottleTimeMs);
    if (stream() != null) _o.setStream(stream().unpack());
    else _o.setStream(null);
  }
  public static int pack(FlatBufferBuilder builder, DescribeStreamResponseT _o) {
    if (_o == null) return 0;
    int _status = _o.getStatus() == null ? 0 : com.automq.elasticstream.client.flatc.header.Status.pack(builder, _o.getStatus());
    int _stream = _o.getStream() == null ? 0 : com.automq.elasticstream.client.flatc.header.Stream.pack(builder, _o.getStream());
    return createDescribeStreamResponse(
      builder,
      _status,
      _o.getThrottleTimeMs(),
      _stream);
  }
}

