// automatically generated by the FlatBuffers compiler, do not modify

package com.automq.elasticstream.client.flatc.header;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DescribePlacementManagerClusterResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static DescribePlacementManagerClusterResponse getRootAsDescribePlacementManagerClusterResponse(ByteBuffer _bb) { return getRootAsDescribePlacementManagerClusterResponse(_bb, new DescribePlacementManagerClusterResponse()); }
  public static DescribePlacementManagerClusterResponse getRootAsDescribePlacementManagerClusterResponse(ByteBuffer _bb, DescribePlacementManagerClusterResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DescribePlacementManagerClusterResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.automq.elasticstream.client.flatc.header.Status status() { return status(new com.automq.elasticstream.client.flatc.header.Status()); }
  public com.automq.elasticstream.client.flatc.header.Status status(com.automq.elasticstream.client.flatc.header.Status obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.automq.elasticstream.client.flatc.header.PlacementManagerCluster cluster() { return cluster(new com.automq.elasticstream.client.flatc.header.PlacementManagerCluster()); }
  public com.automq.elasticstream.client.flatc.header.PlacementManagerCluster cluster(com.automq.elasticstream.client.flatc.header.PlacementManagerCluster obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createDescribePlacementManagerClusterResponse(FlatBufferBuilder builder,
      int statusOffset,
      int clusterOffset) {
    builder.startTable(2);
    DescribePlacementManagerClusterResponse.addCluster(builder, clusterOffset);
    DescribePlacementManagerClusterResponse.addStatus(builder, statusOffset);
    return DescribePlacementManagerClusterResponse.endDescribePlacementManagerClusterResponse(builder);
  }

  public static void startDescribePlacementManagerClusterResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addStatus(FlatBufferBuilder builder, int statusOffset) { builder.addOffset(0, statusOffset, 0); }
  public static void addCluster(FlatBufferBuilder builder, int clusterOffset) { builder.addOffset(1, clusterOffset, 0); }
  public static int endDescribePlacementManagerClusterResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // status
    builder.required(o, 6);  // cluster
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DescribePlacementManagerClusterResponse get(int j) { return get(new DescribePlacementManagerClusterResponse(), j); }
    public DescribePlacementManagerClusterResponse get(DescribePlacementManagerClusterResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public DescribePlacementManagerClusterResponseT unpack() {
    DescribePlacementManagerClusterResponseT _o = new DescribePlacementManagerClusterResponseT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(DescribePlacementManagerClusterResponseT _o) {
    if (status() != null) _o.setStatus(status().unpack());
    else _o.setStatus(null);
    if (cluster() != null) _o.setCluster(cluster().unpack());
    else _o.setCluster(null);
  }
  public static int pack(FlatBufferBuilder builder, DescribePlacementManagerClusterResponseT _o) {
    if (_o == null) return 0;
    int _status = _o.getStatus() == null ? 0 : com.automq.elasticstream.client.flatc.header.Status.pack(builder, _o.getStatus());
    int _cluster = _o.getCluster() == null ? 0 : com.automq.elasticstream.client.flatc.header.PlacementManagerCluster.pack(builder, _o.getCluster());
    return createDescribePlacementManagerClusterResponse(
      builder,
      _status,
      _cluster);
  }
}

