// automatically generated by the FlatBuffers compiler, do not modify

package com.automq.elasticstream.client.flatc.header;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ListRangeRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static ListRangeRequest getRootAsListRangeRequest(ByteBuffer _bb) { return getRootAsListRangeRequest(_bb, new ListRangeRequest()); }
  public static ListRangeRequest getRootAsListRangeRequest(ByteBuffer _bb, ListRangeRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ListRangeRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int timeoutMs() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public com.automq.elasticstream.client.flatc.header.ListRangeCriteria criteria() { return criteria(new com.automq.elasticstream.client.flatc.header.ListRangeCriteria()); }
  public com.automq.elasticstream.client.flatc.header.ListRangeCriteria criteria(com.automq.elasticstream.client.flatc.header.ListRangeCriteria obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createListRangeRequest(FlatBufferBuilder builder,
      int timeoutMs,
      int criteriaOffset) {
    builder.startTable(2);
    ListRangeRequest.addCriteria(builder, criteriaOffset);
    ListRangeRequest.addTimeoutMs(builder, timeoutMs);
    return ListRangeRequest.endListRangeRequest(builder);
  }

  public static void startListRangeRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addTimeoutMs(FlatBufferBuilder builder, int timeoutMs) { builder.addInt(0, timeoutMs, 0); }
  public static void addCriteria(FlatBufferBuilder builder, int criteriaOffset) { builder.addOffset(1, criteriaOffset, 0); }
  public static int endListRangeRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // criteria
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ListRangeRequest get(int j) { return get(new ListRangeRequest(), j); }
    public ListRangeRequest get(ListRangeRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ListRangeRequestT unpack() {
    ListRangeRequestT _o = new ListRangeRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ListRangeRequestT _o) {
    int _oTimeoutMs = timeoutMs();
    _o.setTimeoutMs(_oTimeoutMs);
    if (criteria() != null) _o.setCriteria(criteria().unpack());
    else _o.setCriteria(null);
  }
  public static int pack(FlatBufferBuilder builder, ListRangeRequestT _o) {
    if (_o == null) return 0;
    int _criteria = _o.getCriteria() == null ? 0 : com.automq.elasticstream.client.flatc.header.ListRangeCriteria.pack(builder, _o.getCriteria());
    return createListRangeRequest(
      builder,
      _o.getTimeoutMs(),
      _criteria);
  }
}

