// automatically generated by the FlatBuffers compiler, do not modify

package com.automq.elasticstream.client.flatc.header;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class ReportMetricsRequestT {
  private com.automq.elasticstream.client.flatc.header.DataNodeT dataNode;
  private com.automq.elasticstream.client.flatc.header.DataNodeMetricsT metrics;

  public com.automq.elasticstream.client.flatc.header.DataNodeT getDataNode() { return dataNode; }

  public void setDataNode(com.automq.elasticstream.client.flatc.header.DataNodeT dataNode) { this.dataNode = dataNode; }

  public com.automq.elasticstream.client.flatc.header.DataNodeMetricsT getMetrics() { return metrics; }

  public void setMetrics(com.automq.elasticstream.client.flatc.header.DataNodeMetricsT metrics) { this.metrics = metrics; }


  public ReportMetricsRequestT() {
    this.dataNode = null;
    this.metrics = null;
  }
}

