// automatically generated by the FlatBuffers compiler, do not modify

package com.automq.elasticstream.client.flatc.header;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ReportMetricsRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static ReportMetricsRequest getRootAsReportMetricsRequest(ByteBuffer _bb) { return getRootAsReportMetricsRequest(_bb, new ReportMetricsRequest()); }
  public static ReportMetricsRequest getRootAsReportMetricsRequest(ByteBuffer _bb, ReportMetricsRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ReportMetricsRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.automq.elasticstream.client.flatc.header.DataNode dataNode() { return dataNode(new com.automq.elasticstream.client.flatc.header.DataNode()); }
  public com.automq.elasticstream.client.flatc.header.DataNode dataNode(com.automq.elasticstream.client.flatc.header.DataNode obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.automq.elasticstream.client.flatc.header.DataNodeMetrics metrics() { return metrics(new com.automq.elasticstream.client.flatc.header.DataNodeMetrics()); }
  public com.automq.elasticstream.client.flatc.header.DataNodeMetrics metrics(com.automq.elasticstream.client.flatc.header.DataNodeMetrics obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createReportMetricsRequest(FlatBufferBuilder builder,
      int dataNodeOffset,
      int metricsOffset) {
    builder.startTable(2);
    ReportMetricsRequest.addMetrics(builder, metricsOffset);
    ReportMetricsRequest.addDataNode(builder, dataNodeOffset);
    return ReportMetricsRequest.endReportMetricsRequest(builder);
  }

  public static void startReportMetricsRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addDataNode(FlatBufferBuilder builder, int dataNodeOffset) { builder.addOffset(0, dataNodeOffset, 0); }
  public static void addMetrics(FlatBufferBuilder builder, int metricsOffset) { builder.addOffset(1, metricsOffset, 0); }
  public static int endReportMetricsRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ReportMetricsRequest get(int j) { return get(new ReportMetricsRequest(), j); }
    public ReportMetricsRequest get(ReportMetricsRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ReportMetricsRequestT unpack() {
    ReportMetricsRequestT _o = new ReportMetricsRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ReportMetricsRequestT _o) {
    if (dataNode() != null) _o.setDataNode(dataNode().unpack());
    else _o.setDataNode(null);
    if (metrics() != null) _o.setMetrics(metrics().unpack());
    else _o.setMetrics(null);
  }
  public static int pack(FlatBufferBuilder builder, ReportMetricsRequestT _o) {
    if (_o == null) return 0;
    int _dataNode = _o.getDataNode() == null ? 0 : com.automq.elasticstream.client.flatc.header.DataNode.pack(builder, _o.getDataNode());
    int _metrics = _o.getMetrics() == null ? 0 : com.automq.elasticstream.client.flatc.header.DataNodeMetrics.pack(builder, _o.getMetrics());
    return createReportMetricsRequest(
      builder,
      _dataNode,
      _metrics);
  }
}

