// automatically generated by the FlatBuffers compiler, do not modify

package com.automq.elasticstream.client.flatc.header;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class StreamT {
  private long streamId;
  private byte replica;
  private byte ackCount;
  private long retentionPeriodMs;

  public long getStreamId() { return streamId; }

  public void setStreamId(long streamId) { this.streamId = streamId; }

  public byte getReplica() { return replica; }

  public void setReplica(byte replica) { this.replica = replica; }

  public byte getAckCount() { return ackCount; }

  public void setAckCount(byte ackCount) { this.ackCount = ackCount; }

  public long getRetentionPeriodMs() { return retentionPeriodMs; }

  public void setRetentionPeriodMs(long retentionPeriodMs) { this.retentionPeriodMs = retentionPeriodMs; }


  public StreamT() {
    this.streamId = -1L;
    this.replica = 0;
    this.ackCount = 0;
    this.retentionPeriodMs = 0L;
  }
}

