// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AppendRequestT struct {
	TimeoutMs int32 `json:"timeout_ms"`
	Entries []*AppendEntryT `json:"entries"`
}

func (t *AppendRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	entriesOffset := flatbuffers.UOffsetT(0)
	if t.Entries != nil {
		entriesLength := len(t.Entries)
		entriesOffsets := make([]flatbuffers.UOffsetT, entriesLength)
		for j := 0; j < entriesLength; j++ {
			entriesOffsets[j] = t.Entries[j].Pack(builder)
		}
		AppendRequestStartEntriesVector(builder, entriesLength)
		for j := entriesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(entriesOffsets[j])
		}
		entriesOffset = builder.EndVector(entriesLength)
	}
	AppendRequestStart(builder)
	AppendRequestAddTimeoutMs(builder, t.TimeoutMs)
	AppendRequestAddEntries(builder, entriesOffset)
	return AppendRequestEnd(builder)
}

func (rcv *AppendRequest) UnPackTo(t *AppendRequestT) {
	t.TimeoutMs = rcv.TimeoutMs()
	entriesLength := rcv.EntriesLength()
	t.Entries = make([]*AppendEntryT, entriesLength)
	for j := 0; j < entriesLength; j++ {
		x := AppendEntry{}
		rcv.Entries(&x, j)
		t.Entries[j] = x.UnPack()
	}
}

func (rcv *AppendRequest) UnPack() *AppendRequestT {
	if rcv == nil { return nil }
	t := &AppendRequestT{}
	rcv.UnPackTo(t)
	return t
}

type AppendRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAppendRequest(buf []byte, offset flatbuffers.UOffsetT) *AppendRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AppendRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAppendRequest(buf []byte, offset flatbuffers.UOffsetT) *AppendRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AppendRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AppendRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AppendRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AppendRequest) TimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendRequest) MutateTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *AppendRequest) Entries(obj *AppendEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AppendRequest) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AppendRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AppendRequestAddTimeoutMs(builder *flatbuffers.Builder, timeoutMs int32) {
	builder.PrependInt32Slot(0, timeoutMs, 0)
}
func AppendRequestAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(entries), 0)
}
func AppendRequestStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AppendRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
