// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeleteStreamResponseT struct {
	Status *StatusT `json:"status"`
	Stream *StreamT `json:"stream"`
	ThrottleTimeMs int32 `json:"throttle_time_ms"`
}

func (t *DeleteStreamResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	statusOffset := t.Status.Pack(builder)
	streamOffset := t.Stream.Pack(builder)
	DeleteStreamResponseStart(builder)
	DeleteStreamResponseAddStatus(builder, statusOffset)
	DeleteStreamResponseAddStream(builder, streamOffset)
	DeleteStreamResponseAddThrottleTimeMs(builder, t.ThrottleTimeMs)
	return DeleteStreamResponseEnd(builder)
}

func (rcv *DeleteStreamResponse) UnPackTo(t *DeleteStreamResponseT) {
	t.Status = rcv.Status(nil).UnPack()
	t.Stream = rcv.Stream(nil).UnPack()
	t.ThrottleTimeMs = rcv.ThrottleTimeMs()
}

func (rcv *DeleteStreamResponse) UnPack() *DeleteStreamResponseT {
	if rcv == nil { return nil }
	t := &DeleteStreamResponseT{}
	rcv.UnPackTo(t)
	return t
}

type DeleteStreamResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteStreamResponse(buf []byte, offset flatbuffers.UOffsetT) *DeleteStreamResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteStreamResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDeleteStreamResponse(buf []byte, offset flatbuffers.UOffsetT) *DeleteStreamResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeleteStreamResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DeleteStreamResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteStreamResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteStreamResponse) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DeleteStreamResponse) Stream(obj *Stream) *Stream {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Stream)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DeleteStreamResponse) ThrottleTimeMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DeleteStreamResponse) MutateThrottleTimeMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func DeleteStreamResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func DeleteStreamResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func DeleteStreamResponseAddStream(builder *flatbuffers.Builder, stream flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(stream), 0)
}
func DeleteStreamResponseAddThrottleTimeMs(builder *flatbuffers.Builder, throttleTimeMs int32) {
	builder.PrependInt32Slot(2, throttleTimeMs, 0)
}
func DeleteStreamResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
