// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DescribeRangesResponseT struct {
	ThrottleTimeMs int32 `json:"throttle_time_ms"`
	DescribeResponses []*DescribeRangeResultT `json:"describe_responses"`
	Status *StatusT `json:"status"`
}

func (t *DescribeRangesResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	describeResponsesOffset := flatbuffers.UOffsetT(0)
	if t.DescribeResponses != nil {
		describeResponsesLength := len(t.DescribeResponses)
		describeResponsesOffsets := make([]flatbuffers.UOffsetT, describeResponsesLength)
		for j := 0; j < describeResponsesLength; j++ {
			describeResponsesOffsets[j] = t.DescribeResponses[j].Pack(builder)
		}
		DescribeRangesResponseStartDescribeResponsesVector(builder, describeResponsesLength)
		for j := describeResponsesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(describeResponsesOffsets[j])
		}
		describeResponsesOffset = builder.EndVector(describeResponsesLength)
	}
	statusOffset := t.Status.Pack(builder)
	DescribeRangesResponseStart(builder)
	DescribeRangesResponseAddThrottleTimeMs(builder, t.ThrottleTimeMs)
	DescribeRangesResponseAddDescribeResponses(builder, describeResponsesOffset)
	DescribeRangesResponseAddStatus(builder, statusOffset)
	return DescribeRangesResponseEnd(builder)
}

func (rcv *DescribeRangesResponse) UnPackTo(t *DescribeRangesResponseT) {
	t.ThrottleTimeMs = rcv.ThrottleTimeMs()
	describeResponsesLength := rcv.DescribeResponsesLength()
	t.DescribeResponses = make([]*DescribeRangeResultT, describeResponsesLength)
	for j := 0; j < describeResponsesLength; j++ {
		x := DescribeRangeResult{}
		rcv.DescribeResponses(&x, j)
		t.DescribeResponses[j] = x.UnPack()
	}
	t.Status = rcv.Status(nil).UnPack()
}

func (rcv *DescribeRangesResponse) UnPack() *DescribeRangesResponseT {
	if rcv == nil { return nil }
	t := &DescribeRangesResponseT{}
	rcv.UnPackTo(t)
	return t
}

type DescribeRangesResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDescribeRangesResponse(buf []byte, offset flatbuffers.UOffsetT) *DescribeRangesResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DescribeRangesResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDescribeRangesResponse(buf []byte, offset flatbuffers.UOffsetT) *DescribeRangesResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DescribeRangesResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DescribeRangesResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DescribeRangesResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DescribeRangesResponse) ThrottleTimeMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DescribeRangesResponse) MutateThrottleTimeMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *DescribeRangesResponse) DescribeResponses(obj *DescribeRangeResult, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DescribeRangesResponse) DescribeResponsesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DescribeRangesResponse) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func DescribeRangesResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func DescribeRangesResponseAddThrottleTimeMs(builder *flatbuffers.Builder, throttleTimeMs int32) {
	builder.PrependInt32Slot(0, throttleTimeMs, 0)
}
func DescribeRangesResponseAddDescribeResponses(builder *flatbuffers.Builder, describeResponses flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(describeResponses), 0)
}
func DescribeRangesResponseStartDescribeResponsesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DescribeRangesResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(status), 0)
}
func DescribeRangesResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
