// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FetchResultEntryT struct {
	Status *StatusT `json:"status"`
	StreamId int64 `json:"stream_id"`
	BatchCount int32 `json:"batch_count"`
}

func (t *FetchResultEntryT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	statusOffset := t.Status.Pack(builder)
	FetchResultEntryStart(builder)
	FetchResultEntryAddStatus(builder, statusOffset)
	FetchResultEntryAddStreamId(builder, t.StreamId)
	FetchResultEntryAddBatchCount(builder, t.BatchCount)
	return FetchResultEntryEnd(builder)
}

func (rcv *FetchResultEntry) UnPackTo(t *FetchResultEntryT) {
	t.Status = rcv.Status(nil).UnPack()
	t.StreamId = rcv.StreamId()
	t.BatchCount = rcv.BatchCount()
}

func (rcv *FetchResultEntry) UnPack() *FetchResultEntryT {
	if rcv == nil { return nil }
	t := &FetchResultEntryT{}
	rcv.UnPackTo(t)
	return t
}

type FetchResultEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsFetchResultEntry(buf []byte, offset flatbuffers.UOffsetT) *FetchResultEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FetchResultEntry{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFetchResultEntry(buf []byte, offset flatbuffers.UOffsetT) *FetchResultEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FetchResultEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FetchResultEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FetchResultEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FetchResultEntry) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *FetchResultEntry) StreamId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *FetchResultEntry) MutateStreamId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *FetchResultEntry) BatchCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FetchResultEntry) MutateBatchCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func FetchResultEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FetchResultEntryAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func FetchResultEntryAddStreamId(builder *flatbuffers.Builder, streamId int64) {
	builder.PrependInt64Slot(1, streamId, -1)
}
func FetchResultEntryAddBatchCount(builder *flatbuffers.Builder, batchCount int32) {
	builder.PrependInt32Slot(2, batchCount, 0)
}
func FetchResultEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
