// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IdAllocationResponseT struct {
	Id int32 `json:"id"`
	Status *StatusT `json:"status"`
}

func (t *IdAllocationResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	statusOffset := t.Status.Pack(builder)
	IdAllocationResponseStart(builder)
	IdAllocationResponseAddId(builder, t.Id)
	IdAllocationResponseAddStatus(builder, statusOffset)
	return IdAllocationResponseEnd(builder)
}

func (rcv *IdAllocationResponse) UnPackTo(t *IdAllocationResponseT) {
	t.Id = rcv.Id()
	t.Status = rcv.Status(nil).UnPack()
}

func (rcv *IdAllocationResponse) UnPack() *IdAllocationResponseT {
	if rcv == nil { return nil }
	t := &IdAllocationResponseT{}
	rcv.UnPackTo(t)
	return t
}

type IdAllocationResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsIdAllocationResponse(buf []byte, offset flatbuffers.UOffsetT) *IdAllocationResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IdAllocationResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsIdAllocationResponse(buf []byte, offset flatbuffers.UOffsetT) *IdAllocationResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IdAllocationResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *IdAllocationResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IdAllocationResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IdAllocationResponse) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *IdAllocationResponse) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *IdAllocationResponse) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func IdAllocationResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func IdAllocationResponseAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func IdAllocationResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(status), 0)
}
func IdAllocationResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
