// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RangeCriteriaT struct {
	NodeId int32 `json:"node_id"`
	StreamId int64 `json:"stream_id"`
}

func (t *RangeCriteriaT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	RangeCriteriaStart(builder)
	RangeCriteriaAddNodeId(builder, t.NodeId)
	RangeCriteriaAddStreamId(builder, t.StreamId)
	return RangeCriteriaEnd(builder)
}

func (rcv *RangeCriteria) UnPackTo(t *RangeCriteriaT) {
	t.NodeId = rcv.NodeId()
	t.StreamId = rcv.StreamId()
}

func (rcv *RangeCriteria) UnPack() *RangeCriteriaT {
	if rcv == nil { return nil }
	t := &RangeCriteriaT{}
	rcv.UnPackTo(t)
	return t
}

type RangeCriteria struct {
	_tab flatbuffers.Table
}

func GetRootAsRangeCriteria(buf []byte, offset flatbuffers.UOffsetT) *RangeCriteria {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RangeCriteria{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRangeCriteria(buf []byte, offset flatbuffers.UOffsetT) *RangeCriteria {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RangeCriteria{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RangeCriteria) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RangeCriteria) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RangeCriteria) NodeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *RangeCriteria) MutateNodeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *RangeCriteria) StreamId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *RangeCriteria) MutateStreamId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func RangeCriteriaStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RangeCriteriaAddNodeId(builder *flatbuffers.Builder, nodeId int32) {
	builder.PrependInt32Slot(0, nodeId, -1)
}
func RangeCriteriaAddStreamId(builder *flatbuffers.Builder, streamId int64) {
	builder.PrependInt64Slot(1, streamId, -1)
}
func RangeCriteriaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
