// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SealRangesResponseT struct {
	Status *StatusT `json:"status"`
	Results []*SealRangeResultT `json:"results"`
	ThrottleTimeMs int32 `json:"throttle_time_ms"`
}

func (t *SealRangesResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	statusOffset := t.Status.Pack(builder)
	resultsOffset := flatbuffers.UOffsetT(0)
	if t.Results != nil {
		resultsLength := len(t.Results)
		resultsOffsets := make([]flatbuffers.UOffsetT, resultsLength)
		for j := 0; j < resultsLength; j++ {
			resultsOffsets[j] = t.Results[j].Pack(builder)
		}
		SealRangesResponseStartResultsVector(builder, resultsLength)
		for j := resultsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(resultsOffsets[j])
		}
		resultsOffset = builder.EndVector(resultsLength)
	}
	SealRangesResponseStart(builder)
	SealRangesResponseAddStatus(builder, statusOffset)
	SealRangesResponseAddResults(builder, resultsOffset)
	SealRangesResponseAddThrottleTimeMs(builder, t.ThrottleTimeMs)
	return SealRangesResponseEnd(builder)
}

func (rcv *SealRangesResponse) UnPackTo(t *SealRangesResponseT) {
	t.Status = rcv.Status(nil).UnPack()
	resultsLength := rcv.ResultsLength()
	t.Results = make([]*SealRangeResultT, resultsLength)
	for j := 0; j < resultsLength; j++ {
		x := SealRangeResult{}
		rcv.Results(&x, j)
		t.Results[j] = x.UnPack()
	}
	t.ThrottleTimeMs = rcv.ThrottleTimeMs()
}

func (rcv *SealRangesResponse) UnPack() *SealRangesResponseT {
	if rcv == nil { return nil }
	t := &SealRangesResponseT{}
	rcv.UnPackTo(t)
	return t
}

type SealRangesResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSealRangesResponse(buf []byte, offset flatbuffers.UOffsetT) *SealRangesResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SealRangesResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSealRangesResponse(buf []byte, offset flatbuffers.UOffsetT) *SealRangesResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SealRangesResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SealRangesResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SealRangesResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SealRangesResponse) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SealRangesResponse) Results(obj *SealRangeResult, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SealRangesResponse) ResultsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SealRangesResponse) ThrottleTimeMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SealRangesResponse) MutateThrottleTimeMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func SealRangesResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SealRangesResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func SealRangesResponseAddResults(builder *flatbuffers.Builder, results flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(results), 0)
}
func SealRangesResponseStartResultsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SealRangesResponseAddThrottleTimeMs(builder *flatbuffers.Builder, throttleTimeMs int32) {
	builder.PrependInt32Slot(2, throttleTimeMs, 0)
}
func SealRangesResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
