// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UpdateStreamRequestT struct {
	TimeoutMs int32 `json:"timeout_ms"`
	Stream *StreamT `json:"stream"`
}

func (t *UpdateStreamRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	streamOffset := t.Stream.Pack(builder)
	UpdateStreamRequestStart(builder)
	UpdateStreamRequestAddTimeoutMs(builder, t.TimeoutMs)
	UpdateStreamRequestAddStream(builder, streamOffset)
	return UpdateStreamRequestEnd(builder)
}

func (rcv *UpdateStreamRequest) UnPackTo(t *UpdateStreamRequestT) {
	t.TimeoutMs = rcv.TimeoutMs()
	t.Stream = rcv.Stream(nil).UnPack()
}

func (rcv *UpdateStreamRequest) UnPack() *UpdateStreamRequestT {
	if rcv == nil { return nil }
	t := &UpdateStreamRequestT{}
	rcv.UnPackTo(t)
	return t
}

type UpdateStreamRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateStreamRequest(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateStreamRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUpdateStreamRequest(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateStreamRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UpdateStreamRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateStreamRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateStreamRequest) TimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UpdateStreamRequest) MutateTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *UpdateStreamRequest) Stream(obj *Stream) *Stream {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Stream)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func UpdateStreamRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UpdateStreamRequestAddTimeoutMs(builder *flatbuffers.Builder, timeoutMs int32) {
	builder.PrependInt32Slot(0, timeoutMs, 0)
}
func UpdateStreamRequestAddStream(builder *flatbuffers.Builder, stream flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(stream), 0)
}
func UpdateStreamRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
