// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UpdateStreamsRequestT struct {
	TimeoutMs int32 `json:"timeout_ms"`
	Streams []*StreamT `json:"streams"`
}

func (t *UpdateStreamsRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	streamsOffset := flatbuffers.UOffsetT(0)
	if t.Streams != nil {
		streamsLength := len(t.Streams)
		streamsOffsets := make([]flatbuffers.UOffsetT, streamsLength)
		for j := 0; j < streamsLength; j++ {
			streamsOffsets[j] = t.Streams[j].Pack(builder)
		}
		UpdateStreamsRequestStartStreamsVector(builder, streamsLength)
		for j := streamsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(streamsOffsets[j])
		}
		streamsOffset = builder.EndVector(streamsLength)
	}
	UpdateStreamsRequestStart(builder)
	UpdateStreamsRequestAddTimeoutMs(builder, t.TimeoutMs)
	UpdateStreamsRequestAddStreams(builder, streamsOffset)
	return UpdateStreamsRequestEnd(builder)
}

func (rcv *UpdateStreamsRequest) UnPackTo(t *UpdateStreamsRequestT) {
	t.TimeoutMs = rcv.TimeoutMs()
	streamsLength := rcv.StreamsLength()
	t.Streams = make([]*StreamT, streamsLength)
	for j := 0; j < streamsLength; j++ {
		x := Stream{}
		rcv.Streams(&x, j)
		t.Streams[j] = x.UnPack()
	}
}

func (rcv *UpdateStreamsRequest) UnPack() *UpdateStreamsRequestT {
	if rcv == nil { return nil }
	t := &UpdateStreamsRequestT{}
	rcv.UnPackTo(t)
	return t
}

type UpdateStreamsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateStreamsRequest(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateStreamsRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUpdateStreamsRequest(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateStreamsRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UpdateStreamsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateStreamsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateStreamsRequest) TimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UpdateStreamsRequest) MutateTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *UpdateStreamsRequest) Streams(obj *Stream, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *UpdateStreamsRequest) StreamsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func UpdateStreamsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UpdateStreamsRequestAddTimeoutMs(builder *flatbuffers.Builder, timeoutMs int32) {
	builder.PrependInt32Slot(0, timeoutMs, 0)
}
func UpdateStreamsRequestAddStreams(builder *flatbuffers.Builder, streams flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(streams), 0)
}
func UpdateStreamsRequestStartStreamsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func UpdateStreamsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
