// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UpdateStreamsResponseT struct {
	ThrottleTimeMs int32 `json:"throttle_time_ms"`
	UpdateResponses []*UpdateStreamResultT `json:"update_responses"`
	Status *StatusT `json:"status"`
}

func (t *UpdateStreamsResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	updateResponsesOffset := flatbuffers.UOffsetT(0)
	if t.UpdateResponses != nil {
		updateResponsesLength := len(t.UpdateResponses)
		updateResponsesOffsets := make([]flatbuffers.UOffsetT, updateResponsesLength)
		for j := 0; j < updateResponsesLength; j++ {
			updateResponsesOffsets[j] = t.UpdateResponses[j].Pack(builder)
		}
		UpdateStreamsResponseStartUpdateResponsesVector(builder, updateResponsesLength)
		for j := updateResponsesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(updateResponsesOffsets[j])
		}
		updateResponsesOffset = builder.EndVector(updateResponsesLength)
	}
	statusOffset := t.Status.Pack(builder)
	UpdateStreamsResponseStart(builder)
	UpdateStreamsResponseAddThrottleTimeMs(builder, t.ThrottleTimeMs)
	UpdateStreamsResponseAddUpdateResponses(builder, updateResponsesOffset)
	UpdateStreamsResponseAddStatus(builder, statusOffset)
	return UpdateStreamsResponseEnd(builder)
}

func (rcv *UpdateStreamsResponse) UnPackTo(t *UpdateStreamsResponseT) {
	t.ThrottleTimeMs = rcv.ThrottleTimeMs()
	updateResponsesLength := rcv.UpdateResponsesLength()
	t.UpdateResponses = make([]*UpdateStreamResultT, updateResponsesLength)
	for j := 0; j < updateResponsesLength; j++ {
		x := UpdateStreamResult{}
		rcv.UpdateResponses(&x, j)
		t.UpdateResponses[j] = x.UnPack()
	}
	t.Status = rcv.Status(nil).UnPack()
}

func (rcv *UpdateStreamsResponse) UnPack() *UpdateStreamsResponseT {
	if rcv == nil { return nil }
	t := &UpdateStreamsResponseT{}
	rcv.UnPackTo(t)
	return t
}

type UpdateStreamsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateStreamsResponse(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateStreamsResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUpdateStreamsResponse(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateStreamsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UpdateStreamsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateStreamsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateStreamsResponse) ThrottleTimeMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UpdateStreamsResponse) MutateThrottleTimeMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *UpdateStreamsResponse) UpdateResponses(obj *UpdateStreamResult, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *UpdateStreamsResponse) UpdateResponsesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *UpdateStreamsResponse) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func UpdateStreamsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UpdateStreamsResponseAddThrottleTimeMs(builder *flatbuffers.Builder, throttleTimeMs int32) {
	builder.PrependInt32Slot(0, throttleTimeMs, 0)
}
func UpdateStreamsResponseAddUpdateResponses(builder *flatbuffers.Builder, updateResponses flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(updateResponses), 0)
}
func UpdateStreamsResponseStartUpdateResponsesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func UpdateStreamsResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(status), 0)
}
func UpdateStreamsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
