// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DescribePlacementDriverClusterResponseT struct {
	Status *StatusT `json:"status"`
	Cluster *PlacementDriverClusterT `json:"cluster"`
}

func (t *DescribePlacementDriverClusterResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	statusOffset := t.Status.Pack(builder)
	clusterOffset := t.Cluster.Pack(builder)
	DescribePlacementDriverClusterResponseStart(builder)
	DescribePlacementDriverClusterResponseAddStatus(builder, statusOffset)
	DescribePlacementDriverClusterResponseAddCluster(builder, clusterOffset)
	return DescribePlacementDriverClusterResponseEnd(builder)
}

func (rcv *DescribePlacementDriverClusterResponse) UnPackTo(t *DescribePlacementDriverClusterResponseT) {
	t.Status = rcv.Status(nil).UnPack()
	t.Cluster = rcv.Cluster(nil).UnPack()
}

func (rcv *DescribePlacementDriverClusterResponse) UnPack() *DescribePlacementDriverClusterResponseT {
	if rcv == nil { return nil }
	t := &DescribePlacementDriverClusterResponseT{}
	rcv.UnPackTo(t)
	return t
}

type DescribePlacementDriverClusterResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDescribePlacementDriverClusterResponse(buf []byte, offset flatbuffers.UOffsetT) *DescribePlacementDriverClusterResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DescribePlacementDriverClusterResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDescribePlacementDriverClusterResponse(buf []byte, offset flatbuffers.UOffsetT) *DescribePlacementDriverClusterResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DescribePlacementDriverClusterResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DescribePlacementDriverClusterResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DescribePlacementDriverClusterResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DescribePlacementDriverClusterResponse) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DescribePlacementDriverClusterResponse) Cluster(obj *PlacementDriverCluster) *PlacementDriverCluster {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PlacementDriverCluster)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func DescribePlacementDriverClusterResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DescribePlacementDriverClusterResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func DescribePlacementDriverClusterResponseAddCluster(builder *flatbuffers.Builder, cluster flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(cluster), 0)
}
func DescribePlacementDriverClusterResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
