// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import "strconv"

type ErrorCode int16

const (
	ErrorCodeERROR_CODE_UNSPECIFIED        ErrorCode = 0
	ErrorCodeENCODE                        ErrorCode = 1
	ErrorCodeDECODE                        ErrorCode = 2
	ErrorCodeUNEXPECTED                    ErrorCode = 3
	ErrorCodeOK                            ErrorCode = 1200
	ErrorCodeNO_NEW_RECORD                 ErrorCode = 1204
	ErrorCodeBAD_REQUEST                   ErrorCode = 1400
	ErrorCodeUNAUTHORIZED                  ErrorCode = 1401
	ErrorCodePAYMENT_REQUIRED              ErrorCode = 1402
	ErrorCodeFORBIDDEN                     ErrorCode = 1403
	ErrorCodeNOT_FOUND                     ErrorCode = 1404
	ErrorCodeMETHOD_NOT_ALLOWED            ErrorCode = 1405
	ErrorCodePRECONDITION_FAILED           ErrorCode = 1412
	ErrorCodePAYLOAD_TOO_LARGE             ErrorCode = 1413
	ErrorCodeTOO_MANY_REQUESTS             ErrorCode = 1429
	ErrorCodeHEADER_FIELDS_TOO_LARGE       ErrorCode = 1431
	ErrorCodeUNAVAILABLE_FOR_LEGAL_REASONS ErrorCode = 1451
	ErrorCodeRANGE_ALREADY_SEALED          ErrorCode = 1460
	ErrorCodeOFFSET_OVERFLOW               ErrorCode = 1461
	ErrorCodeRANGE_NOT_FOUND               ErrorCode = 1462
	ErrorCodeOFFSET_OUT_OF_RANGE_BOUNDS    ErrorCode = 1463
	ErrorCodeAPPEND_TO_COMMITTED_OFFSET    ErrorCode = 1464
	ErrorCodeAPPEND_TO_PENDING_OFFSET      ErrorCode = 1465
	ErrorCodeAPPEND_TO_OVERTAKEN_OFFSET    ErrorCode = 1466
	ErrorCodeCREATE_RANGE_BEFORE_SEAL      ErrorCode = 1470
	ErrorCodeEXPIRED_RANGE_EPOCH           ErrorCode = 1471
	ErrorCodeOBJECT_NOT_FOUND              ErrorCode = 1472
	ErrorCodeNO_MATCH_RECORDS_IN_OBJECT    ErrorCode = 1473
	ErrorCodeOBJECT_OPERATOR_UNINITIALIZED ErrorCode = 1474
	ErrorCodeOBJECT_PARSE_ERROR            ErrorCode = 1475
	ErrorCodeREQUEST_OBJECT_STORE_ERROR    ErrorCode = 1476
	ErrorCodeRECORDS_BLOCKS_NOT_CONTINUOUS ErrorCode = 1477
	ErrorCodeSTREAM_ALREADY_CLOSED         ErrorCode = 1478
	ErrorCodeREPLICA_NOT_ENOUGH            ErrorCode = 1479
	ErrorCodeRECORDS_PARSE_ERROR           ErrorCode = 1480
	ErrorCodeALL_REPLICAS_FETCH_FAILED     ErrorCode = 1481
	ErrorCodeRPC_TIMEOUT                   ErrorCode = 1482
	ErrorCodeBAD_ADDRESS                   ErrorCode = 1483
	ErrorCodeCONNECT_REFUSED               ErrorCode = 1484
	ErrorCodeCONNECT_FAIL                  ErrorCode = 1485
	ErrorCodeCONNECT_TIMEOUT               ErrorCode = 1486
	ErrorCodeCONNECT_DISABLE_NAGLE_FAIL    ErrorCode = 1487
	ErrorCodeSTREAM_NOT_EXIST              ErrorCode = 1488
	ErrorCodeUNSUPPORTED_OPERATION         ErrorCode = 1498
	ErrorCodeUNKNOWN_OPERATION             ErrorCode = 1499
	ErrorCodePD_INTERNAL_SERVER_ERROR      ErrorCode = 1500
	ErrorCodePD_NOT_IMPLEMENTED            ErrorCode = 1501
	ErrorCodePD_NO_AVAILABLE_RS            ErrorCode = 1502
	ErrorCodePD_NOT_LEADER                 ErrorCode = 1503
	ErrorCodePD_COMPACTED                  ErrorCode = 1504
	ErrorCodeRS_INTERNAL_SERVER_ERROR      ErrorCode = 2500
	ErrorCodeRS_NOT_IMPLEMENTED            ErrorCode = 2501
	ErrorCodeRS_DATA_CORRUPTED             ErrorCode = 2502
	ErrorCodeRS_CREATE_RANGE               ErrorCode = 2503
	ErrorCodeRS_SEAL_RANGE                 ErrorCode = 2504
)

var EnumNamesErrorCode = map[ErrorCode]string{
	ErrorCodeERROR_CODE_UNSPECIFIED:        "ERROR_CODE_UNSPECIFIED",
	ErrorCodeENCODE:                        "ENCODE",
	ErrorCodeDECODE:                        "DECODE",
	ErrorCodeUNEXPECTED:                    "UNEXPECTED",
	ErrorCodeOK:                            "OK",
	ErrorCodeNO_NEW_RECORD:                 "NO_NEW_RECORD",
	ErrorCodeBAD_REQUEST:                   "BAD_REQUEST",
	ErrorCodeUNAUTHORIZED:                  "UNAUTHORIZED",
	ErrorCodePAYMENT_REQUIRED:              "PAYMENT_REQUIRED",
	ErrorCodeFORBIDDEN:                     "FORBIDDEN",
	ErrorCodeNOT_FOUND:                     "NOT_FOUND",
	ErrorCodeMETHOD_NOT_ALLOWED:            "METHOD_NOT_ALLOWED",
	ErrorCodePRECONDITION_FAILED:           "PRECONDITION_FAILED",
	ErrorCodePAYLOAD_TOO_LARGE:             "PAYLOAD_TOO_LARGE",
	ErrorCodeTOO_MANY_REQUESTS:             "TOO_MANY_REQUESTS",
	ErrorCodeHEADER_FIELDS_TOO_LARGE:       "HEADER_FIELDS_TOO_LARGE",
	ErrorCodeUNAVAILABLE_FOR_LEGAL_REASONS: "UNAVAILABLE_FOR_LEGAL_REASONS",
	ErrorCodeRANGE_ALREADY_SEALED:          "RANGE_ALREADY_SEALED",
	ErrorCodeOFFSET_OVERFLOW:               "OFFSET_OVERFLOW",
	ErrorCodeRANGE_NOT_FOUND:               "RANGE_NOT_FOUND",
	ErrorCodeOFFSET_OUT_OF_RANGE_BOUNDS:    "OFFSET_OUT_OF_RANGE_BOUNDS",
	ErrorCodeAPPEND_TO_COMMITTED_OFFSET:    "APPEND_TO_COMMITTED_OFFSET",
	ErrorCodeAPPEND_TO_PENDING_OFFSET:      "APPEND_TO_PENDING_OFFSET",
	ErrorCodeAPPEND_TO_OVERTAKEN_OFFSET:    "APPEND_TO_OVERTAKEN_OFFSET",
	ErrorCodeCREATE_RANGE_BEFORE_SEAL:      "CREATE_RANGE_BEFORE_SEAL",
	ErrorCodeEXPIRED_RANGE_EPOCH:           "EXPIRED_RANGE_EPOCH",
	ErrorCodeOBJECT_NOT_FOUND:              "OBJECT_NOT_FOUND",
	ErrorCodeNO_MATCH_RECORDS_IN_OBJECT:    "NO_MATCH_RECORDS_IN_OBJECT",
	ErrorCodeOBJECT_OPERATOR_UNINITIALIZED: "OBJECT_OPERATOR_UNINITIALIZED",
	ErrorCodeOBJECT_PARSE_ERROR:            "OBJECT_PARSE_ERROR",
	ErrorCodeREQUEST_OBJECT_STORE_ERROR:    "REQUEST_OBJECT_STORE_ERROR",
	ErrorCodeRECORDS_BLOCKS_NOT_CONTINUOUS: "RECORDS_BLOCKS_NOT_CONTINUOUS",
	ErrorCodeSTREAM_ALREADY_CLOSED:         "STREAM_ALREADY_CLOSED",
	ErrorCodeREPLICA_NOT_ENOUGH:            "REPLICA_NOT_ENOUGH",
	ErrorCodeRECORDS_PARSE_ERROR:           "RECORDS_PARSE_ERROR",
	ErrorCodeALL_REPLICAS_FETCH_FAILED:     "ALL_REPLICAS_FETCH_FAILED",
	ErrorCodeRPC_TIMEOUT:                   "RPC_TIMEOUT",
	ErrorCodeBAD_ADDRESS:                   "BAD_ADDRESS",
	ErrorCodeCONNECT_REFUSED:               "CONNECT_REFUSED",
	ErrorCodeCONNECT_FAIL:                  "CONNECT_FAIL",
	ErrorCodeCONNECT_TIMEOUT:               "CONNECT_TIMEOUT",
	ErrorCodeCONNECT_DISABLE_NAGLE_FAIL:    "CONNECT_DISABLE_NAGLE_FAIL",
	ErrorCodeSTREAM_NOT_EXIST:              "STREAM_NOT_EXIST",
	ErrorCodeUNSUPPORTED_OPERATION:         "UNSUPPORTED_OPERATION",
	ErrorCodeUNKNOWN_OPERATION:             "UNKNOWN_OPERATION",
	ErrorCodePD_INTERNAL_SERVER_ERROR:      "PD_INTERNAL_SERVER_ERROR",
	ErrorCodePD_NOT_IMPLEMENTED:            "PD_NOT_IMPLEMENTED",
	ErrorCodePD_NO_AVAILABLE_RS:            "PD_NO_AVAILABLE_RS",
	ErrorCodePD_NOT_LEADER:                 "PD_NOT_LEADER",
	ErrorCodePD_COMPACTED:                  "PD_COMPACTED",
	ErrorCodeRS_INTERNAL_SERVER_ERROR:      "RS_INTERNAL_SERVER_ERROR",
	ErrorCodeRS_NOT_IMPLEMENTED:            "RS_NOT_IMPLEMENTED",
	ErrorCodeRS_DATA_CORRUPTED:             "RS_DATA_CORRUPTED",
	ErrorCodeRS_CREATE_RANGE:               "RS_CREATE_RANGE",
	ErrorCodeRS_SEAL_RANGE:                 "RS_SEAL_RANGE",
}

var EnumValuesErrorCode = map[string]ErrorCode{
	"ERROR_CODE_UNSPECIFIED":        ErrorCodeERROR_CODE_UNSPECIFIED,
	"ENCODE":                        ErrorCodeENCODE,
	"DECODE":                        ErrorCodeDECODE,
	"UNEXPECTED":                    ErrorCodeUNEXPECTED,
	"OK":                            ErrorCodeOK,
	"NO_NEW_RECORD":                 ErrorCodeNO_NEW_RECORD,
	"BAD_REQUEST":                   ErrorCodeBAD_REQUEST,
	"UNAUTHORIZED":                  ErrorCodeUNAUTHORIZED,
	"PAYMENT_REQUIRED":              ErrorCodePAYMENT_REQUIRED,
	"FORBIDDEN":                     ErrorCodeFORBIDDEN,
	"NOT_FOUND":                     ErrorCodeNOT_FOUND,
	"METHOD_NOT_ALLOWED":            ErrorCodeMETHOD_NOT_ALLOWED,
	"PRECONDITION_FAILED":           ErrorCodePRECONDITION_FAILED,
	"PAYLOAD_TOO_LARGE":             ErrorCodePAYLOAD_TOO_LARGE,
	"TOO_MANY_REQUESTS":             ErrorCodeTOO_MANY_REQUESTS,
	"HEADER_FIELDS_TOO_LARGE":       ErrorCodeHEADER_FIELDS_TOO_LARGE,
	"UNAVAILABLE_FOR_LEGAL_REASONS": ErrorCodeUNAVAILABLE_FOR_LEGAL_REASONS,
	"RANGE_ALREADY_SEALED":          ErrorCodeRANGE_ALREADY_SEALED,
	"OFFSET_OVERFLOW":               ErrorCodeOFFSET_OVERFLOW,
	"RANGE_NOT_FOUND":               ErrorCodeRANGE_NOT_FOUND,
	"OFFSET_OUT_OF_RANGE_BOUNDS":    ErrorCodeOFFSET_OUT_OF_RANGE_BOUNDS,
	"APPEND_TO_COMMITTED_OFFSET":    ErrorCodeAPPEND_TO_COMMITTED_OFFSET,
	"APPEND_TO_PENDING_OFFSET":      ErrorCodeAPPEND_TO_PENDING_OFFSET,
	"APPEND_TO_OVERTAKEN_OFFSET":    ErrorCodeAPPEND_TO_OVERTAKEN_OFFSET,
	"CREATE_RANGE_BEFORE_SEAL":      ErrorCodeCREATE_RANGE_BEFORE_SEAL,
	"EXPIRED_RANGE_EPOCH":           ErrorCodeEXPIRED_RANGE_EPOCH,
	"OBJECT_NOT_FOUND":              ErrorCodeOBJECT_NOT_FOUND,
	"NO_MATCH_RECORDS_IN_OBJECT":    ErrorCodeNO_MATCH_RECORDS_IN_OBJECT,
	"OBJECT_OPERATOR_UNINITIALIZED": ErrorCodeOBJECT_OPERATOR_UNINITIALIZED,
	"OBJECT_PARSE_ERROR":            ErrorCodeOBJECT_PARSE_ERROR,
	"REQUEST_OBJECT_STORE_ERROR":    ErrorCodeREQUEST_OBJECT_STORE_ERROR,
	"RECORDS_BLOCKS_NOT_CONTINUOUS": ErrorCodeRECORDS_BLOCKS_NOT_CONTINUOUS,
	"STREAM_ALREADY_CLOSED":         ErrorCodeSTREAM_ALREADY_CLOSED,
	"REPLICA_NOT_ENOUGH":            ErrorCodeREPLICA_NOT_ENOUGH,
	"RECORDS_PARSE_ERROR":           ErrorCodeRECORDS_PARSE_ERROR,
	"ALL_REPLICAS_FETCH_FAILED":     ErrorCodeALL_REPLICAS_FETCH_FAILED,
	"RPC_TIMEOUT":                   ErrorCodeRPC_TIMEOUT,
	"BAD_ADDRESS":                   ErrorCodeBAD_ADDRESS,
	"CONNECT_REFUSED":               ErrorCodeCONNECT_REFUSED,
	"CONNECT_FAIL":                  ErrorCodeCONNECT_FAIL,
	"CONNECT_TIMEOUT":               ErrorCodeCONNECT_TIMEOUT,
	"CONNECT_DISABLE_NAGLE_FAIL":    ErrorCodeCONNECT_DISABLE_NAGLE_FAIL,
	"STREAM_NOT_EXIST":              ErrorCodeSTREAM_NOT_EXIST,
	"UNSUPPORTED_OPERATION":         ErrorCodeUNSUPPORTED_OPERATION,
	"UNKNOWN_OPERATION":             ErrorCodeUNKNOWN_OPERATION,
	"PD_INTERNAL_SERVER_ERROR":      ErrorCodePD_INTERNAL_SERVER_ERROR,
	"PD_NOT_IMPLEMENTED":            ErrorCodePD_NOT_IMPLEMENTED,
	"PD_NO_AVAILABLE_RS":            ErrorCodePD_NO_AVAILABLE_RS,
	"PD_NOT_LEADER":                 ErrorCodePD_NOT_LEADER,
	"PD_COMPACTED":                  ErrorCodePD_COMPACTED,
	"RS_INTERNAL_SERVER_ERROR":      ErrorCodeRS_INTERNAL_SERVER_ERROR,
	"RS_NOT_IMPLEMENTED":            ErrorCodeRS_NOT_IMPLEMENTED,
	"RS_DATA_CORRUPTED":             ErrorCodeRS_DATA_CORRUPTED,
	"RS_CREATE_RANGE":               ErrorCodeRS_CREATE_RANGE,
	"RS_SEAL_RANGE":                 ErrorCodeRS_SEAL_RANGE,
}

func (v ErrorCode) String() string {
	if s, ok := EnumNamesErrorCode[v]; ok {
		return s
	}
	return "ErrorCode(" + strconv.FormatInt(int64(v), 10) + ")"
}
