// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlacementDriverClusterT struct {
	Nodes []*PlacementDriverNodeT `json:"nodes"`
}

func (t *PlacementDriverClusterT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	nodesOffset := flatbuffers.UOffsetT(0)
	if t.Nodes != nil {
		nodesLength := len(t.Nodes)
		nodesOffsets := make([]flatbuffers.UOffsetT, nodesLength)
		for j := 0; j < nodesLength; j++ {
			nodesOffsets[j] = t.Nodes[j].Pack(builder)
		}
		PlacementDriverClusterStartNodesVector(builder, nodesLength)
		for j := nodesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(nodesOffsets[j])
		}
		nodesOffset = builder.EndVector(nodesLength)
	}
	PlacementDriverClusterStart(builder)
	PlacementDriverClusterAddNodes(builder, nodesOffset)
	return PlacementDriverClusterEnd(builder)
}

func (rcv *PlacementDriverCluster) UnPackTo(t *PlacementDriverClusterT) {
	nodesLength := rcv.NodesLength()
	t.Nodes = make([]*PlacementDriverNodeT, nodesLength)
	for j := 0; j < nodesLength; j++ {
		x := PlacementDriverNode{}
		rcv.Nodes(&x, j)
		t.Nodes[j] = x.UnPack()
	}
}

func (rcv *PlacementDriverCluster) UnPack() *PlacementDriverClusterT {
	if rcv == nil { return nil }
	t := &PlacementDriverClusterT{}
	rcv.UnPackTo(t)
	return t
}

type PlacementDriverCluster struct {
	_tab flatbuffers.Table
}

func GetRootAsPlacementDriverCluster(buf []byte, offset flatbuffers.UOffsetT) *PlacementDriverCluster {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlacementDriverCluster{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPlacementDriverCluster(buf []byte, offset flatbuffers.UOffsetT) *PlacementDriverCluster {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlacementDriverCluster{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *PlacementDriverCluster) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlacementDriverCluster) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlacementDriverCluster) Nodes(obj *PlacementDriverNode, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PlacementDriverCluster) NodesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PlacementDriverClusterStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PlacementDriverClusterAddNodes(builder *flatbuffers.Builder, nodes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodes), 0)
}
func PlacementDriverClusterStartNodesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PlacementDriverClusterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
