// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RangeRequestT struct {
	TimeoutMs int32 `json:"timeout_ms"`
	Key []byte `json:"key"`
	RangeEnd []byte `json:"range_end"`
	Limit int64 `json:"limit"`
}

func (t *RangeRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	keyOffset := flatbuffers.UOffsetT(0)
	if t.Key != nil {
		keyOffset = builder.CreateByteString(t.Key)
	}
	rangeEndOffset := flatbuffers.UOffsetT(0)
	if t.RangeEnd != nil {
		rangeEndOffset = builder.CreateByteString(t.RangeEnd)
	}
	RangeRequestStart(builder)
	RangeRequestAddTimeoutMs(builder, t.TimeoutMs)
	RangeRequestAddKey(builder, keyOffset)
	RangeRequestAddRangeEnd(builder, rangeEndOffset)
	RangeRequestAddLimit(builder, t.Limit)
	return RangeRequestEnd(builder)
}

func (rcv *RangeRequest) UnPackTo(t *RangeRequestT) {
	t.TimeoutMs = rcv.TimeoutMs()
	t.Key = rcv.KeyBytes()
	t.RangeEnd = rcv.RangeEndBytes()
	t.Limit = rcv.Limit()
}

func (rcv *RangeRequest) UnPack() *RangeRequestT {
	if rcv == nil { return nil }
	t := &RangeRequestT{}
	rcv.UnPackTo(t)
	return t
}

type RangeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRangeRequest(buf []byte, offset flatbuffers.UOffsetT) *RangeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RangeRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRangeRequest(buf []byte, offset flatbuffers.UOffsetT) *RangeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RangeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RangeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RangeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RangeRequest) TimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RangeRequest) MutateTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *RangeRequest) Key(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *RangeRequest) KeyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RangeRequest) KeyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RangeRequest) MutateKey(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *RangeRequest) RangeEnd(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *RangeRequest) RangeEndLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RangeRequest) RangeEndBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RangeRequest) MutateRangeEnd(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *RangeRequest) Limit() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RangeRequest) MutateLimit(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func RangeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func RangeRequestAddTimeoutMs(builder *flatbuffers.Builder, timeoutMs int32) {
	builder.PrependInt32Slot(0, timeoutMs, 0)
}
func RangeRequestAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func RangeRequestStartKeyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RangeRequestAddRangeEnd(builder *flatbuffers.Builder, rangeEnd flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(rangeEnd), 0)
}
func RangeRequestStartRangeEndVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RangeRequestAddLimit(builder *flatbuffers.Builder, limit int64) {
	builder.PrependInt64Slot(3, limit, 0)
}
func RangeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
