// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RangeServerT struct {
	ServerId int32 `json:"server_id"`
	AdvertiseAddr string `json:"advertise_addr"`
}

func (t *RangeServerT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	advertiseAddrOffset := flatbuffers.UOffsetT(0)
	if t.AdvertiseAddr != "" {
		advertiseAddrOffset = builder.CreateString(t.AdvertiseAddr)
	}
	RangeServerStart(builder)
	RangeServerAddServerId(builder, t.ServerId)
	RangeServerAddAdvertiseAddr(builder, advertiseAddrOffset)
	return RangeServerEnd(builder)
}

func (rcv *RangeServer) UnPackTo(t *RangeServerT) {
	t.ServerId = rcv.ServerId()
	t.AdvertiseAddr = string(rcv.AdvertiseAddr())
}

func (rcv *RangeServer) UnPack() *RangeServerT {
	if rcv == nil { return nil }
	t := &RangeServerT{}
	rcv.UnPackTo(t)
	return t
}

type RangeServer struct {
	_tab flatbuffers.Table
}

func GetRootAsRangeServer(buf []byte, offset flatbuffers.UOffsetT) *RangeServer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RangeServer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRangeServer(buf []byte, offset flatbuffers.UOffsetT) *RangeServer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RangeServer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RangeServer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RangeServer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RangeServer) ServerId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *RangeServer) MutateServerId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *RangeServer) AdvertiseAddr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RangeServerStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RangeServerAddServerId(builder *flatbuffers.Builder, serverId int32) {
	builder.PrependInt32Slot(0, serverId, -1)
}
func RangeServerAddAdvertiseAddr(builder *flatbuffers.Builder, advertiseAddr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(advertiseAddr), 0)
}
func RangeServerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
