// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RangeProgressT struct {
	StreamId int64 `json:"stream_id"`
	RangeIndex int32 `json:"range_index"`
	ConfirmOffset int64 `json:"confirm_offset"`
}

func (t *RangeProgressT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	RangeProgressStart(builder)
	RangeProgressAddStreamId(builder, t.StreamId)
	RangeProgressAddRangeIndex(builder, t.RangeIndex)
	RangeProgressAddConfirmOffset(builder, t.ConfirmOffset)
	return RangeProgressEnd(builder)
}

func (rcv *RangeProgress) UnPackTo(t *RangeProgressT) {
	t.StreamId = rcv.StreamId()
	t.RangeIndex = rcv.RangeIndex()
	t.ConfirmOffset = rcv.ConfirmOffset()
}

func (rcv *RangeProgress) UnPack() *RangeProgressT {
	if rcv == nil { return nil }
	t := &RangeProgressT{}
	rcv.UnPackTo(t)
	return t
}

type RangeProgress struct {
	_tab flatbuffers.Table
}

func GetRootAsRangeProgress(buf []byte, offset flatbuffers.UOffsetT) *RangeProgress {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RangeProgress{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRangeProgress(buf []byte, offset flatbuffers.UOffsetT) *RangeProgress {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RangeProgress{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RangeProgress) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RangeProgress) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RangeProgress) StreamId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RangeProgress) MutateStreamId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *RangeProgress) RangeIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RangeProgress) MutateRangeIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *RangeProgress) ConfirmOffset() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RangeProgress) MutateConfirmOffset(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func RangeProgressStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RangeProgressAddStreamId(builder *flatbuffers.Builder, streamId int64) {
	builder.PrependInt64Slot(0, streamId, 0)
}
func RangeProgressAddRangeIndex(builder *flatbuffers.Builder, rangeIndex int32) {
	builder.PrependInt32Slot(1, rangeIndex, 0)
}
func RangeProgressAddConfirmOffset(builder *flatbuffers.Builder, confirmOffset int64) {
	builder.PrependInt64Slot(2, confirmOffset, 0)
}
func RangeProgressEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
