// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReportReplicaProgressResponseT struct {
	Status *StatusT `json:"status"`
	ThrottleTimeMs int32 `json:"throttle_time_ms"`
}

func (t *ReportReplicaProgressResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	statusOffset := t.Status.Pack(builder)
	ReportReplicaProgressResponseStart(builder)
	ReportReplicaProgressResponseAddStatus(builder, statusOffset)
	ReportReplicaProgressResponseAddThrottleTimeMs(builder, t.ThrottleTimeMs)
	return ReportReplicaProgressResponseEnd(builder)
}

func (rcv *ReportReplicaProgressResponse) UnPackTo(t *ReportReplicaProgressResponseT) {
	t.Status = rcv.Status(nil).UnPack()
	t.ThrottleTimeMs = rcv.ThrottleTimeMs()
}

func (rcv *ReportReplicaProgressResponse) UnPack() *ReportReplicaProgressResponseT {
	if rcv == nil { return nil }
	t := &ReportReplicaProgressResponseT{}
	rcv.UnPackTo(t)
	return t
}

type ReportReplicaProgressResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsReportReplicaProgressResponse(buf []byte, offset flatbuffers.UOffsetT) *ReportReplicaProgressResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReportReplicaProgressResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsReportReplicaProgressResponse(buf []byte, offset flatbuffers.UOffsetT) *ReportReplicaProgressResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReportReplicaProgressResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ReportReplicaProgressResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReportReplicaProgressResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReportReplicaProgressResponse) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ReportReplicaProgressResponse) ThrottleTimeMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ReportReplicaProgressResponse) MutateThrottleTimeMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func ReportReplicaProgressResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ReportReplicaProgressResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func ReportReplicaProgressResponseAddThrottleTimeMs(builder *flatbuffers.Builder, throttleTimeMs int32) {
	builder.PrependInt32Slot(1, throttleTimeMs, 0)
}
func ReportReplicaProgressResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
