// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReportRangeProgressRequestT struct {
	TimeoutMs int32 `json:"timeout_ms"`
	RangeServer *RangeServerT `json:"range_server"`
	RangeProgress []*RangeProgressT `json:"range_progress"`
}

func (t *ReportRangeProgressRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	rangeServerOffset := t.RangeServer.Pack(builder)
	rangeProgressOffset := flatbuffers.UOffsetT(0)
	if t.RangeProgress != nil {
		rangeProgressLength := len(t.RangeProgress)
		rangeProgressOffsets := make([]flatbuffers.UOffsetT, rangeProgressLength)
		for j := 0; j < rangeProgressLength; j++ {
			rangeProgressOffsets[j] = t.RangeProgress[j].Pack(builder)
		}
		ReportRangeProgressRequestStartRangeProgressVector(builder, rangeProgressLength)
		for j := rangeProgressLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(rangeProgressOffsets[j])
		}
		rangeProgressOffset = builder.EndVector(rangeProgressLength)
	}
	ReportRangeProgressRequestStart(builder)
	ReportRangeProgressRequestAddTimeoutMs(builder, t.TimeoutMs)
	ReportRangeProgressRequestAddRangeServer(builder, rangeServerOffset)
	ReportRangeProgressRequestAddRangeProgress(builder, rangeProgressOffset)
	return ReportRangeProgressRequestEnd(builder)
}

func (rcv *ReportRangeProgressRequest) UnPackTo(t *ReportRangeProgressRequestT) {
	t.TimeoutMs = rcv.TimeoutMs()
	t.RangeServer = rcv.RangeServer(nil).UnPack()
	rangeProgressLength := rcv.RangeProgressLength()
	t.RangeProgress = make([]*RangeProgressT, rangeProgressLength)
	for j := 0; j < rangeProgressLength; j++ {
		x := RangeProgress{}
		rcv.RangeProgress(&x, j)
		t.RangeProgress[j] = x.UnPack()
	}
}

func (rcv *ReportRangeProgressRequest) UnPack() *ReportRangeProgressRequestT {
	if rcv == nil { return nil }
	t := &ReportRangeProgressRequestT{}
	rcv.UnPackTo(t)
	return t
}

type ReportRangeProgressRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsReportRangeProgressRequest(buf []byte, offset flatbuffers.UOffsetT) *ReportRangeProgressRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReportRangeProgressRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsReportRangeProgressRequest(buf []byte, offset flatbuffers.UOffsetT) *ReportRangeProgressRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReportRangeProgressRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ReportRangeProgressRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReportRangeProgressRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReportRangeProgressRequest) TimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ReportRangeProgressRequest) MutateTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *ReportRangeProgressRequest) RangeServer(obj *RangeServer) *RangeServer {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(RangeServer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ReportRangeProgressRequest) RangeProgress(obj *RangeProgress, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ReportRangeProgressRequest) RangeProgressLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ReportRangeProgressRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ReportRangeProgressRequestAddTimeoutMs(builder *flatbuffers.Builder, timeoutMs int32) {
	builder.PrependInt32Slot(0, timeoutMs, 0)
}
func ReportRangeProgressRequestAddRangeServer(builder *flatbuffers.Builder, rangeServer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(rangeServer), 0)
}
func ReportRangeProgressRequestAddRangeProgress(builder *flatbuffers.Builder, rangeProgress flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(rangeProgress), 0)
}
func ReportRangeProgressRequestStartRangeProgressVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ReportRangeProgressRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
