// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResourceT struct {
	Type ResourceType `json:"type"`
	Data []byte `json:"data"`
}

func (t *ResourceT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	dataOffset := flatbuffers.UOffsetT(0)
	if t.Data != nil {
		dataOffset = builder.CreateByteString(t.Data)
	}
	ResourceStart(builder)
	ResourceAddType(builder, t.Type)
	ResourceAddData(builder, dataOffset)
	return ResourceEnd(builder)
}

func (rcv *Resource) UnPackTo(t *ResourceT) {
	t.Type = rcv.Type()
	t.Data = rcv.DataBytes()
}

func (rcv *Resource) UnPack() *ResourceT {
	if rcv == nil { return nil }
	t := &ResourceT{}
	rcv.UnPackTo(t)
	return t
}

type Resource struct {
	_tab flatbuffers.Table
}

func GetRootAsResource(buf []byte, offset flatbuffers.UOffsetT) *Resource {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Resource{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsResource(buf []byte, offset flatbuffers.UOffsetT) *Resource {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Resource{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Resource) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Resource) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Resource) Type() ResourceType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ResourceType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Resource) MutateType(n ResourceType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *Resource) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Resource) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Resource) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Resource) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func ResourceStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ResourceAddType(builder *flatbuffers.Builder, type_ ResourceType) {
	builder.PrependInt8Slot(0, int8(type_), 0)
}
func ResourceAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func ResourceStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ResourceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
