// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import "strconv"

type ResponseOpType byte

const (
	ResponseOpTypeRANGE        ResponseOpType = 0
	ResponseOpTypePUT          ResponseOpType = 1
	ResponseOpTypeDELETE_RANGE ResponseOpType = 2
	ResponseOpTypeTXN          ResponseOpType = 3
)

var EnumNamesResponseOpType = map[ResponseOpType]string{
	ResponseOpTypeRANGE:        "RANGE",
	ResponseOpTypePUT:          "PUT",
	ResponseOpTypeDELETE_RANGE: "DELETE_RANGE",
	ResponseOpTypeTXN:          "TXN",
}

var EnumValuesResponseOpType = map[string]ResponseOpType{
	"RANGE":        ResponseOpTypeRANGE,
	"PUT":          ResponseOpTypePUT,
	"DELETE_RANGE": ResponseOpTypeDELETE_RANGE,
	"TXN":          ResponseOpTypeTXN,
}

func (v ResponseOpType) String() string {
	if s, ok := EnumNamesResponseOpType[v]; ok {
		return s
	}
	return "ResponseOpType(" + strconv.FormatInt(int64(v), 10) + ")"
}
