// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrimStreamRequestT struct {
	TimeoutMs int32 `json:"timeout_ms"`
	StreamId int64 `json:"stream_id"`
	MinOffset int64 `json:"min_offset"`
}

func (t *TrimStreamRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	TrimStreamRequestStart(builder)
	TrimStreamRequestAddTimeoutMs(builder, t.TimeoutMs)
	TrimStreamRequestAddStreamId(builder, t.StreamId)
	TrimStreamRequestAddMinOffset(builder, t.MinOffset)
	return TrimStreamRequestEnd(builder)
}

func (rcv *TrimStreamRequest) UnPackTo(t *TrimStreamRequestT) {
	t.TimeoutMs = rcv.TimeoutMs()
	t.StreamId = rcv.StreamId()
	t.MinOffset = rcv.MinOffset()
}

func (rcv *TrimStreamRequest) UnPack() *TrimStreamRequestT {
	if rcv == nil { return nil }
	t := &TrimStreamRequestT{}
	rcv.UnPackTo(t)
	return t
}

type TrimStreamRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTrimStreamRequest(buf []byte, offset flatbuffers.UOffsetT) *TrimStreamRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrimStreamRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTrimStreamRequest(buf []byte, offset flatbuffers.UOffsetT) *TrimStreamRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrimStreamRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TrimStreamRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrimStreamRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TrimStreamRequest) TimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TrimStreamRequest) MutateTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TrimStreamRequest) StreamId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TrimStreamRequest) MutateStreamId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *TrimStreamRequest) MinOffset() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TrimStreamRequest) MutateMinOffset(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func TrimStreamRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TrimStreamRequestAddTimeoutMs(builder *flatbuffers.Builder, timeoutMs int32) {
	builder.PrependInt32Slot(0, timeoutMs, 0)
}
func TrimStreamRequestAddStreamId(builder *flatbuffers.Builder, streamId int64) {
	builder.PrependInt64Slot(1, streamId, -1)
}
func TrimStreamRequestAddMinOffset(builder *flatbuffers.Builder, minOffset int64) {
	builder.PrependInt64Slot(2, minOffset, 0)
}
func TrimStreamRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
