// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UpdateStreamEpochResponseT struct {
	Status *StatusT `json:"status"`
	ThrottleTimeMs int32 `json:"throttle_time_ms"`
}

func (t *UpdateStreamEpochResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	statusOffset := t.Status.Pack(builder)
	UpdateStreamEpochResponseStart(builder)
	UpdateStreamEpochResponseAddStatus(builder, statusOffset)
	UpdateStreamEpochResponseAddThrottleTimeMs(builder, t.ThrottleTimeMs)
	return UpdateStreamEpochResponseEnd(builder)
}

func (rcv *UpdateStreamEpochResponse) UnPackTo(t *UpdateStreamEpochResponseT) {
	t.Status = rcv.Status(nil).UnPack()
	t.ThrottleTimeMs = rcv.ThrottleTimeMs()
}

func (rcv *UpdateStreamEpochResponse) UnPack() *UpdateStreamEpochResponseT {
	if rcv == nil { return nil }
	t := &UpdateStreamEpochResponseT{}
	rcv.UnPackTo(t)
	return t
}

type UpdateStreamEpochResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateStreamEpochResponse(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamEpochResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateStreamEpochResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUpdateStreamEpochResponse(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamEpochResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateStreamEpochResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UpdateStreamEpochResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateStreamEpochResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateStreamEpochResponse) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *UpdateStreamEpochResponse) ThrottleTimeMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UpdateStreamEpochResponse) MutateThrottleTimeMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func UpdateStreamEpochResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UpdateStreamEpochResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func UpdateStreamEpochResponseAddThrottleTimeMs(builder *flatbuffers.Builder, throttleTimeMs int32) {
	builder.PrependInt32Slot(1, throttleTimeMs, 0)
}
func UpdateStreamEpochResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
