// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UpdateStreamEpochRequestT struct {
	TimeoutMs int32 `json:"timeout_ms"`
	StreamId int64 `json:"stream_id"`
	Epoch int64 `json:"epoch"`
}

func (t *UpdateStreamEpochRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	UpdateStreamEpochRequestStart(builder)
	UpdateStreamEpochRequestAddTimeoutMs(builder, t.TimeoutMs)
	UpdateStreamEpochRequestAddStreamId(builder, t.StreamId)
	UpdateStreamEpochRequestAddEpoch(builder, t.Epoch)
	return UpdateStreamEpochRequestEnd(builder)
}

func (rcv *UpdateStreamEpochRequest) UnPackTo(t *UpdateStreamEpochRequestT) {
	t.TimeoutMs = rcv.TimeoutMs()
	t.StreamId = rcv.StreamId()
	t.Epoch = rcv.Epoch()
}

func (rcv *UpdateStreamEpochRequest) UnPack() *UpdateStreamEpochRequestT {
	if rcv == nil { return nil }
	t := &UpdateStreamEpochRequestT{}
	rcv.UnPackTo(t)
	return t
}

type UpdateStreamEpochRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateStreamEpochRequest(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamEpochRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateStreamEpochRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUpdateStreamEpochRequest(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamEpochRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateStreamEpochRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UpdateStreamEpochRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateStreamEpochRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateStreamEpochRequest) TimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UpdateStreamEpochRequest) MutateTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *UpdateStreamEpochRequest) StreamId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *UpdateStreamEpochRequest) MutateStreamId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *UpdateStreamEpochRequest) Epoch() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *UpdateStreamEpochRequest) MutateEpoch(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func UpdateStreamEpochRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UpdateStreamEpochRequestAddTimeoutMs(builder *flatbuffers.Builder, timeoutMs int32) {
	builder.PrependInt32Slot(0, timeoutMs, 0)
}
func UpdateStreamEpochRequestAddStreamId(builder *flatbuffers.Builder, streamId int64) {
	builder.PrependInt64Slot(1, streamId, -1)
}
func UpdateStreamEpochRequestAddEpoch(builder *flatbuffers.Builder, epoch int64) {
	builder.PrependInt64Slot(2, epoch, -1)
}
func UpdateStreamEpochRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
