// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AppendResult struct {
	_tab flatbuffers.Table
}

func GetRootAsAppendResult(buf []byte, offset flatbuffers.UOffsetT) *AppendResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AppendResult{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAppendResult(buf []byte, offset flatbuffers.UOffsetT) *AppendResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AppendResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AppendResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AppendResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AppendResult) StreamId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendResult) MutateStreamId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *AppendResult) RequestIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendResult) MutateRequestIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *AppendResult) BaseOffset() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendResult) MutateBaseOffset(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *AppendResult) StreamAppendTimeMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendResult) MutateStreamAppendTimeMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *AppendResult) ErrorCode() ErrorCode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return ErrorCode(rcv._tab.GetUint16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *AppendResult) MutateErrorCode(n ErrorCode) bool {
	return rcv._tab.MutateUint16Slot(12, uint16(n))
}

func (rcv *AppendResult) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AppendResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func AppendResultAddStreamId(builder *flatbuffers.Builder, streamId uint64) {
	builder.PrependUint64Slot(0, streamId, 0)
}
func AppendResultAddRequestIndex(builder *flatbuffers.Builder, requestIndex uint32) {
	builder.PrependUint32Slot(1, requestIndex, 0)
}
func AppendResultAddBaseOffset(builder *flatbuffers.Builder, baseOffset uint64) {
	builder.PrependUint64Slot(2, baseOffset, 0)
}
func AppendResultAddStreamAppendTimeMs(builder *flatbuffers.Builder, streamAppendTimeMs uint64) {
	builder.PrependUint64Slot(3, streamAppendTimeMs, 0)
}
func AppendResultAddErrorCode(builder *flatbuffers.Builder, errorCode ErrorCode) {
	builder.PrependUint16Slot(4, uint16(errorCode), 0)
}
func AppendResultAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(errorMessage), 0)
}
func AppendResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
