// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AppendResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsAppendResponse(buf []byte, offset flatbuffers.UOffsetT) *AppendResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AppendResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAppendResponse(buf []byte, offset flatbuffers.UOffsetT) *AppendResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AppendResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AppendResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AppendResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AppendResponse) ThrottleTimeMs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendResponse) MutateThrottleTimeMs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *AppendResponse) AppendResponses(obj *AppendResult, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AppendResponse) AppendResponsesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AppendResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AppendResponseAddThrottleTimeMs(builder *flatbuffers.Builder, throttleTimeMs uint32) {
	builder.PrependUint32Slot(0, throttleTimeMs, 0)
}
func AppendResponseAddAppendResponses(builder *flatbuffers.Builder, appendResponses flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(appendResponses), 0)
}
func AppendResponseStartAppendResponsesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AppendResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
