// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DescribeRangeResult struct {
	_tab flatbuffers.Table
}

func GetRootAsDescribeRangeResult(buf []byte, offset flatbuffers.UOffsetT) *DescribeRangeResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DescribeRangeResult{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDescribeRangeResult(buf []byte, offset flatbuffers.UOffsetT) *DescribeRangeResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DescribeRangeResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DescribeRangeResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DescribeRangeResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DescribeRangeResult) StreamId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DescribeRangeResult) MutateStreamId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *DescribeRangeResult) ErrorCode() ErrorCode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ErrorCode(rcv._tab.GetUint16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DescribeRangeResult) MutateErrorCode(n ErrorCode) bool {
	return rcv._tab.MutateUint16Slot(6, uint16(n))
}

func (rcv *DescribeRangeResult) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DescribeRangeResult) Ranges(obj *Range) *Range {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Range)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func DescribeRangeResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func DescribeRangeResultAddStreamId(builder *flatbuffers.Builder, streamId uint64) {
	builder.PrependUint64Slot(0, streamId, 0)
}
func DescribeRangeResultAddErrorCode(builder *flatbuffers.Builder, errorCode ErrorCode) {
	builder.PrependUint16Slot(1, uint16(errorCode), 0)
}
func DescribeRangeResultAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(errorMessage), 0)
}
func DescribeRangeResultAddRanges(builder *flatbuffers.Builder, ranges flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(ranges), 0)
}
func DescribeRangeResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
