// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import "strconv"

type ErrorCode uint16

const (
	ErrorCodeNone            ErrorCode = 0
	ErrorCodeUnknown         ErrorCode = 1
	ErrorCodeInvalid_Request ErrorCode = 2
)

var EnumNamesErrorCode = map[ErrorCode]string{
	ErrorCodeNone:            "None",
	ErrorCodeUnknown:         "Unknown",
	ErrorCodeInvalid_Request: "Invalid_Request",
}

var EnumValuesErrorCode = map[string]ErrorCode{
	"None":            ErrorCodeNone,
	"Unknown":         ErrorCodeUnknown,
	"Invalid_Request": ErrorCodeInvalid_Request,
}

func (v ErrorCode) String() string {
	if s, ok := EnumNamesErrorCode[v]; ok {
		return s
	}
	return "ErrorCode(" + strconv.FormatInt(int64(v), 10) + ")"
}
