// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import "strconv"

type ErrorCode int16

const (
	ErrorCodeNONE            ErrorCode = 0
	ErrorCodeUNKNOWN         ErrorCode = 1
	ErrorCodeINVALID_REQUEST ErrorCode = 2
)

var EnumNamesErrorCode = map[ErrorCode]string{
	ErrorCodeNONE:            "NONE",
	ErrorCodeUNKNOWN:         "UNKNOWN",
	ErrorCodeINVALID_REQUEST: "INVALID_REQUEST",
}

var EnumValuesErrorCode = map[string]ErrorCode{
	"NONE":            ErrorCodeNONE,
	"UNKNOWN":         ErrorCodeUNKNOWN,
	"INVALID_REQUEST": ErrorCodeINVALID_REQUEST,
}

func (v ErrorCode) String() string {
	if s, ok := EnumNamesErrorCode[v]; ok {
		return s
	}
	return "ErrorCode(" + strconv.FormatInt(int64(v), 10) + ")"
}
