// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FetchRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsFetchRequest(buf []byte, offset flatbuffers.UOffsetT) *FetchRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FetchRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFetchRequest(buf []byte, offset flatbuffers.UOffsetT) *FetchRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FetchRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FetchRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FetchRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FetchRequest) MaxWaitMs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FetchRequest) MutateMaxWaitMs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *FetchRequest) MinBytes() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FetchRequest) MutateMinBytes(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *FetchRequest) FetchRequests(obj *FetchInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FetchRequest) FetchRequestsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func FetchRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FetchRequestAddMaxWaitMs(builder *flatbuffers.Builder, maxWaitMs uint32) {
	builder.PrependUint32Slot(0, maxWaitMs, 0)
}
func FetchRequestAddMinBytes(builder *flatbuffers.Builder, minBytes uint32) {
	builder.PrependUint32Slot(1, minBytes, 0)
}
func FetchRequestAddFetchRequests(builder *flatbuffers.Builder, fetchRequests flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(fetchRequests), 0)
}
func FetchRequestStartFetchRequestsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FetchRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
