// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HeartbeatResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsHeartbeatResponse(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeartbeatResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsHeartbeatResponse(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HeartbeatResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *HeartbeatResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeartbeatResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HeartbeatResponse) ClientId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HeartbeatResponse) ClientRole() ClientRole {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ClientRole(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *HeartbeatResponse) MutateClientRole(n ClientRole) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *HeartbeatResponse) DataNode(obj *DataNode) *DataNode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DataNode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func HeartbeatResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func HeartbeatResponseAddClientId(builder *flatbuffers.Builder, clientId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(clientId), 0)
}
func HeartbeatResponseAddClientRole(builder *flatbuffers.Builder, clientRole ClientRole) {
	builder.PrependByteSlot(1, byte(clientRole), 0)
}
func HeartbeatResponseAddDataNode(builder *flatbuffers.Builder, dataNode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(dataNode), 0)
}
func HeartbeatResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
