// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RangeId struct {
	_tab flatbuffers.Table
}

func GetRootAsRangeId(buf []byte, offset flatbuffers.UOffsetT) *RangeId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RangeId{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRangeId(buf []byte, offset flatbuffers.UOffsetT) *RangeId {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RangeId{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RangeId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RangeId) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RangeId) StreamId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RangeId) MutateStreamId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *RangeId) RangeIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RangeId) MutateRangeIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func RangeIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RangeIdAddStreamId(builder *flatbuffers.Builder, streamId uint64) {
	builder.PrependUint64Slot(0, streamId, 0)
}
func RangeIdAddRangeIndex(builder *flatbuffers.Builder, rangeIndex uint32) {
	builder.PrependUint32Slot(1, rangeIndex, 0)
}
func RangeIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
