// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReportMetricsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsReportMetricsResponse(buf []byte, offset flatbuffers.UOffsetT) *ReportMetricsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReportMetricsResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsReportMetricsResponse(buf []byte, offset flatbuffers.UOffsetT) *ReportMetricsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReportMetricsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ReportMetricsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReportMetricsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReportMetricsResponse) DataNode(obj *DataNode) *DataNode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DataNode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ReportMetricsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ReportMetricsResponseAddDataNode(builder *flatbuffers.Builder, dataNode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataNode), 0)
}
func ReportMetricsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
