// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Stream struct {
	_tab flatbuffers.Table
}

func GetRootAsStream(buf []byte, offset flatbuffers.UOffsetT) *Stream {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Stream{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStream(buf []byte, offset flatbuffers.UOffsetT) *Stream {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Stream{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Stream) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Stream) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Stream) StreamId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Stream) MutateStreamId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Stream) ReplicaNums() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Stream) MutateReplicaNums(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *Stream) RetentionPeriodMs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Stream) MutateRetentionPeriodMs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func StreamStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func StreamAddStreamId(builder *flatbuffers.Builder, streamId uint64) {
	builder.PrependUint64Slot(0, streamId, 0)
}
func StreamAddReplicaNums(builder *flatbuffers.Builder, replicaNums byte) {
	builder.PrependByteSlot(1, replicaNums, 0)
}
func StreamAddRetentionPeriodMs(builder *flatbuffers.Builder, retentionPeriodMs uint32) {
	builder.PrependUint32Slot(2, retentionPeriodMs, 0)
}
func StreamEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
