// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrimStreamResult struct {
	_tab flatbuffers.Table
}

func GetRootAsTrimStreamResult(buf []byte, offset flatbuffers.UOffsetT) *TrimStreamResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrimStreamResult{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTrimStreamResult(buf []byte, offset flatbuffers.UOffsetT) *TrimStreamResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrimStreamResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TrimStreamResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrimStreamResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TrimStreamResult) TrimmedStream(obj *Stream) *Stream {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Stream)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TrimStreamResult) ErrorCode() ErrorCode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ErrorCode(rcv._tab.GetInt16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TrimStreamResult) MutateErrorCode(n ErrorCode) bool {
	return rcv._tab.MutateInt16Slot(6, int16(n))
}

func (rcv *TrimStreamResult) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TrimStreamResult) Range(obj *Range) *Range {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Range)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TrimStreamResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TrimStreamResultAddTrimmedStream(builder *flatbuffers.Builder, trimmedStream flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trimmedStream), 0)
}
func TrimStreamResultAddErrorCode(builder *flatbuffers.Builder, errorCode ErrorCode) {
	builder.PrependInt16Slot(1, int16(errorCode), 0)
}
func TrimStreamResultAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(errorMessage), 0)
}
func TrimStreamResultAddRange(builder *flatbuffers.Builder, range_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(range_), 0)
}
func TrimStreamResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
