// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package header

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UpdateStreamResult struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateStreamResult(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateStreamResult{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUpdateStreamResult(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateStreamResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UpdateStreamResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateStreamResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateStreamResult) Stream(obj *Stream) *Stream {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Stream)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *UpdateStreamResult) ErrorCode() ErrorCode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ErrorCode(rcv._tab.GetUint16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *UpdateStreamResult) MutateErrorCode(n ErrorCode) bool {
	return rcv._tab.MutateUint16Slot(6, uint16(n))
}

func (rcv *UpdateStreamResult) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UpdateStreamResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UpdateStreamResultAddStream(builder *flatbuffers.Builder, stream flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(stream), 0)
}
func UpdateStreamResultAddErrorCode(builder *flatbuffers.Builder, errorCode ErrorCode) {
	builder.PrependUint16Slot(1, uint16(errorCode), 0)
}
func UpdateStreamResultAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(errorMessage), 0)
}
func UpdateStreamResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
