// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CreateStreamsRequestT struct {
	TimeoutMs int32 `json:"timeout_ms"`
	Streams []*StreamT `json:"streams"`
}

func (t *CreateStreamsRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	streamsOffset := flatbuffers.UOffsetT(0)
	if t.Streams != nil {
		streamsLength := len(t.Streams)
		streamsOffsets := make([]flatbuffers.UOffsetT, streamsLength)
		for j := 0; j < streamsLength; j++ {
			streamsOffsets[j] = t.Streams[j].Pack(builder)
		}
		CreateStreamsRequestStartStreamsVector(builder, streamsLength)
		for j := streamsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(streamsOffsets[j])
		}
		streamsOffset = builder.EndVector(streamsLength)
	}
	CreateStreamsRequestStart(builder)
	CreateStreamsRequestAddTimeoutMs(builder, t.TimeoutMs)
	CreateStreamsRequestAddStreams(builder, streamsOffset)
	return CreateStreamsRequestEnd(builder)
}

func (rcv *CreateStreamsRequest) UnPackTo(t *CreateStreamsRequestT) {
	t.TimeoutMs = rcv.TimeoutMs()
	streamsLength := rcv.StreamsLength()
	t.Streams = make([]*StreamT, streamsLength)
	for j := 0; j < streamsLength; j++ {
		x := Stream{}
		rcv.Streams(&x, j)
		t.Streams[j] = x.UnPack()
	}
}

func (rcv *CreateStreamsRequest) UnPack() *CreateStreamsRequestT {
	if rcv == nil { return nil }
	t := &CreateStreamsRequestT{}
	rcv.UnPackTo(t)
	return t
}

type CreateStreamsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCreateStreamsRequest(buf []byte, offset flatbuffers.UOffsetT) *CreateStreamsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreateStreamsRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCreateStreamsRequest(buf []byte, offset flatbuffers.UOffsetT) *CreateStreamsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CreateStreamsRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *CreateStreamsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreateStreamsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CreateStreamsRequest) TimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CreateStreamsRequest) MutateTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *CreateStreamsRequest) Streams(obj *Stream, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CreateStreamsRequest) StreamsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func CreateStreamsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CreateStreamsRequestAddTimeoutMs(builder *flatbuffers.Builder, timeoutMs int32) {
	builder.PrependInt32Slot(0, timeoutMs, 0)
}
func CreateStreamsRequestAddStreams(builder *flatbuffers.Builder, streams flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(streams), 0)
}
func CreateStreamsRequestStartStreamsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CreateStreamsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
