// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DescribeStreamsResponseT struct {
	ThrottleTimeMs int32 `json:"throttle_time_ms"`
	DescribeResponses []*DescribeStreamResultT `json:"describe_responses"`
	Status *StatusT `json:"status"`
}

func (t *DescribeStreamsResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	describeResponsesOffset := flatbuffers.UOffsetT(0)
	if t.DescribeResponses != nil {
		describeResponsesLength := len(t.DescribeResponses)
		describeResponsesOffsets := make([]flatbuffers.UOffsetT, describeResponsesLength)
		for j := 0; j < describeResponsesLength; j++ {
			describeResponsesOffsets[j] = t.DescribeResponses[j].Pack(builder)
		}
		DescribeStreamsResponseStartDescribeResponsesVector(builder, describeResponsesLength)
		for j := describeResponsesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(describeResponsesOffsets[j])
		}
		describeResponsesOffset = builder.EndVector(describeResponsesLength)
	}
	statusOffset := t.Status.Pack(builder)
	DescribeStreamsResponseStart(builder)
	DescribeStreamsResponseAddThrottleTimeMs(builder, t.ThrottleTimeMs)
	DescribeStreamsResponseAddDescribeResponses(builder, describeResponsesOffset)
	DescribeStreamsResponseAddStatus(builder, statusOffset)
	return DescribeStreamsResponseEnd(builder)
}

func (rcv *DescribeStreamsResponse) UnPackTo(t *DescribeStreamsResponseT) {
	t.ThrottleTimeMs = rcv.ThrottleTimeMs()
	describeResponsesLength := rcv.DescribeResponsesLength()
	t.DescribeResponses = make([]*DescribeStreamResultT, describeResponsesLength)
	for j := 0; j < describeResponsesLength; j++ {
		x := DescribeStreamResult{}
		rcv.DescribeResponses(&x, j)
		t.DescribeResponses[j] = x.UnPack()
	}
	t.Status = rcv.Status(nil).UnPack()
}

func (rcv *DescribeStreamsResponse) UnPack() *DescribeStreamsResponseT {
	if rcv == nil { return nil }
	t := &DescribeStreamsResponseT{}
	rcv.UnPackTo(t)
	return t
}

type DescribeStreamsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDescribeStreamsResponse(buf []byte, offset flatbuffers.UOffsetT) *DescribeStreamsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DescribeStreamsResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDescribeStreamsResponse(buf []byte, offset flatbuffers.UOffsetT) *DescribeStreamsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DescribeStreamsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DescribeStreamsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DescribeStreamsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DescribeStreamsResponse) ThrottleTimeMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DescribeStreamsResponse) MutateThrottleTimeMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *DescribeStreamsResponse) DescribeResponses(obj *DescribeStreamResult, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DescribeStreamsResponse) DescribeResponsesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DescribeStreamsResponse) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func DescribeStreamsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func DescribeStreamsResponseAddThrottleTimeMs(builder *flatbuffers.Builder, throttleTimeMs int32) {
	builder.PrependInt32Slot(0, throttleTimeMs, 0)
}
func DescribeStreamsResponseAddDescribeResponses(builder *flatbuffers.Builder, describeResponses flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(describeResponses), 0)
}
func DescribeStreamsResponseStartDescribeResponsesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DescribeStreamsResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(status), 0)
}
func DescribeStreamsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
