// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DescribeStreamResultT struct {
	Stream *StreamT `json:"stream"`
	Status *StatusT `json:"status"`
}

func (t *DescribeStreamResultT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	streamOffset := t.Stream.Pack(builder)
	statusOffset := t.Status.Pack(builder)
	DescribeStreamResultStart(builder)
	DescribeStreamResultAddStream(builder, streamOffset)
	DescribeStreamResultAddStatus(builder, statusOffset)
	return DescribeStreamResultEnd(builder)
}

func (rcv *DescribeStreamResult) UnPackTo(t *DescribeStreamResultT) {
	t.Stream = rcv.Stream(nil).UnPack()
	t.Status = rcv.Status(nil).UnPack()
}

func (rcv *DescribeStreamResult) UnPack() *DescribeStreamResultT {
	if rcv == nil { return nil }
	t := &DescribeStreamResultT{}
	rcv.UnPackTo(t)
	return t
}

type DescribeStreamResult struct {
	_tab flatbuffers.Table
}

func GetRootAsDescribeStreamResult(buf []byte, offset flatbuffers.UOffsetT) *DescribeStreamResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DescribeStreamResult{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDescribeStreamResult(buf []byte, offset flatbuffers.UOffsetT) *DescribeStreamResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DescribeStreamResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DescribeStreamResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DescribeStreamResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DescribeStreamResult) Stream(obj *Stream) *Stream {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Stream)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DescribeStreamResult) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func DescribeStreamResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DescribeStreamResultAddStream(builder *flatbuffers.Builder, stream flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(stream), 0)
}
func DescribeStreamResultAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(status), 0)
}
func DescribeStreamResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
