// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListRangesRequestT struct {
	TimeoutMs int32 `json:"timeout_ms"`
	RangeOwners []*RangeOwnerT `json:"range_owners"`
}

func (t *ListRangesRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	rangeOwnersOffset := flatbuffers.UOffsetT(0)
	if t.RangeOwners != nil {
		rangeOwnersLength := len(t.RangeOwners)
		rangeOwnersOffsets := make([]flatbuffers.UOffsetT, rangeOwnersLength)
		for j := 0; j < rangeOwnersLength; j++ {
			rangeOwnersOffsets[j] = t.RangeOwners[j].Pack(builder)
		}
		ListRangesRequestStartRangeOwnersVector(builder, rangeOwnersLength)
		for j := rangeOwnersLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(rangeOwnersOffsets[j])
		}
		rangeOwnersOffset = builder.EndVector(rangeOwnersLength)
	}
	ListRangesRequestStart(builder)
	ListRangesRequestAddTimeoutMs(builder, t.TimeoutMs)
	ListRangesRequestAddRangeOwners(builder, rangeOwnersOffset)
	return ListRangesRequestEnd(builder)
}

func (rcv *ListRangesRequest) UnPackTo(t *ListRangesRequestT) {
	t.TimeoutMs = rcv.TimeoutMs()
	rangeOwnersLength := rcv.RangeOwnersLength()
	t.RangeOwners = make([]*RangeOwnerT, rangeOwnersLength)
	for j := 0; j < rangeOwnersLength; j++ {
		x := RangeOwner{}
		rcv.RangeOwners(&x, j)
		t.RangeOwners[j] = x.UnPack()
	}
}

func (rcv *ListRangesRequest) UnPack() *ListRangesRequestT {
	if rcv == nil { return nil }
	t := &ListRangesRequestT{}
	rcv.UnPackTo(t)
	return t
}

type ListRangesRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsListRangesRequest(buf []byte, offset flatbuffers.UOffsetT) *ListRangesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListRangesRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsListRangesRequest(buf []byte, offset flatbuffers.UOffsetT) *ListRangesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ListRangesRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ListRangesRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListRangesRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListRangesRequest) TimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ListRangesRequest) MutateTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *ListRangesRequest) RangeOwners(obj *RangeOwner, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ListRangesRequest) RangeOwnersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ListRangesRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ListRangesRequestAddTimeoutMs(builder *flatbuffers.Builder, timeoutMs int32) {
	builder.PrependInt32Slot(0, timeoutMs, 0)
}
func ListRangesRequestAddRangeOwners(builder *flatbuffers.Builder, rangeOwners flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(rangeOwners), 0)
}
func ListRangesRequestStartRangeOwnersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ListRangesRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
