// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RangeIdT struct {
	StreamId int64 `json:"stream_id"`
	RangeIndex int32 `json:"range_index"`
}

func (t *RangeIdT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	RangeIdStart(builder)
	RangeIdAddStreamId(builder, t.StreamId)
	RangeIdAddRangeIndex(builder, t.RangeIndex)
	return RangeIdEnd(builder)
}

func (rcv *RangeId) UnPackTo(t *RangeIdT) {
	t.StreamId = rcv.StreamId()
	t.RangeIndex = rcv.RangeIndex()
}

func (rcv *RangeId) UnPack() *RangeIdT {
	if rcv == nil { return nil }
	t := &RangeIdT{}
	rcv.UnPackTo(t)
	return t
}

type RangeId struct {
	_tab flatbuffers.Table
}

func GetRootAsRangeId(buf []byte, offset flatbuffers.UOffsetT) *RangeId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RangeId{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRangeId(buf []byte, offset flatbuffers.UOffsetT) *RangeId {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RangeId{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RangeId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RangeId) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RangeId) StreamId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *RangeId) MutateStreamId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *RangeId) RangeIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *RangeId) MutateRangeIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func RangeIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RangeIdAddStreamId(builder *flatbuffers.Builder, streamId int64) {
	builder.PrependInt64Slot(0, streamId, -1)
}
func RangeIdAddRangeIndex(builder *flatbuffers.Builder, rangeIndex int32) {
	builder.PrependInt32Slot(1, rangeIndex, -1)
}
func RangeIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
