// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SyncRangesResultT struct {
	StreamId int64 `json:"stream_id"`
	Ranges []*RangeT `json:"ranges"`
	Status *StatusT `json:"status"`
}

func (t *SyncRangesResultT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	rangesOffset := flatbuffers.UOffsetT(0)
	if t.Ranges != nil {
		rangesLength := len(t.Ranges)
		rangesOffsets := make([]flatbuffers.UOffsetT, rangesLength)
		for j := 0; j < rangesLength; j++ {
			rangesOffsets[j] = t.Ranges[j].Pack(builder)
		}
		SyncRangesResultStartRangesVector(builder, rangesLength)
		for j := rangesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(rangesOffsets[j])
		}
		rangesOffset = builder.EndVector(rangesLength)
	}
	statusOffset := t.Status.Pack(builder)
	SyncRangesResultStart(builder)
	SyncRangesResultAddStreamId(builder, t.StreamId)
	SyncRangesResultAddRanges(builder, rangesOffset)
	SyncRangesResultAddStatus(builder, statusOffset)
	return SyncRangesResultEnd(builder)
}

func (rcv *SyncRangesResult) UnPackTo(t *SyncRangesResultT) {
	t.StreamId = rcv.StreamId()
	rangesLength := rcv.RangesLength()
	t.Ranges = make([]*RangeT, rangesLength)
	for j := 0; j < rangesLength; j++ {
		x := Range{}
		rcv.Ranges(&x, j)
		t.Ranges[j] = x.UnPack()
	}
	t.Status = rcv.Status(nil).UnPack()
}

func (rcv *SyncRangesResult) UnPack() *SyncRangesResultT {
	if rcv == nil { return nil }
	t := &SyncRangesResultT{}
	rcv.UnPackTo(t)
	return t
}

type SyncRangesResult struct {
	_tab flatbuffers.Table
}

func GetRootAsSyncRangesResult(buf []byte, offset flatbuffers.UOffsetT) *SyncRangesResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SyncRangesResult{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSyncRangesResult(buf []byte, offset flatbuffers.UOffsetT) *SyncRangesResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SyncRangesResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SyncRangesResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SyncRangesResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SyncRangesResult) StreamId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *SyncRangesResult) MutateStreamId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *SyncRangesResult) Ranges(obj *Range, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SyncRangesResult) RangesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SyncRangesResult) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SyncRangesResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SyncRangesResultAddStreamId(builder *flatbuffers.Builder, streamId int64) {
	builder.PrependInt64Slot(0, streamId, -1)
}
func SyncRangesResultAddRanges(builder *flatbuffers.Builder, ranges flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(ranges), 0)
}
func SyncRangesResultStartRangesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SyncRangesResultAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(status), 0)
}
func SyncRangesResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
