// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SystemErrorResponseT struct {
	Status *StatusT `json:"status"`
}

func (t *SystemErrorResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	statusOffset := t.Status.Pack(builder)
	SystemErrorResponseStart(builder)
	SystemErrorResponseAddStatus(builder, statusOffset)
	return SystemErrorResponseEnd(builder)
}

func (rcv *SystemErrorResponse) UnPackTo(t *SystemErrorResponseT) {
	t.Status = rcv.Status(nil).UnPack()
}

func (rcv *SystemErrorResponse) UnPack() *SystemErrorResponseT {
	if rcv == nil { return nil }
	t := &SystemErrorResponseT{}
	rcv.UnPackTo(t)
	return t
}

type SystemErrorResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSystemErrorResponse(buf []byte, offset flatbuffers.UOffsetT) *SystemErrorResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SystemErrorResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSystemErrorResponse(buf []byte, offset flatbuffers.UOffsetT) *SystemErrorResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SystemErrorResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SystemErrorResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SystemErrorResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SystemErrorResponse) Status(obj *Status) *Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Status)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SystemErrorResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SystemErrorResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func SystemErrorResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
