// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrimStreamsRequestT struct {
	TimeoutMs int32 `json:"timeout_ms"`
	TrimmedStreams []*TrimmedStreamT `json:"trimmed_streams"`
}

func (t *TrimStreamsRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	trimmedStreamsOffset := flatbuffers.UOffsetT(0)
	if t.TrimmedStreams != nil {
		trimmedStreamsLength := len(t.TrimmedStreams)
		trimmedStreamsOffsets := make([]flatbuffers.UOffsetT, trimmedStreamsLength)
		for j := 0; j < trimmedStreamsLength; j++ {
			trimmedStreamsOffsets[j] = t.TrimmedStreams[j].Pack(builder)
		}
		TrimStreamsRequestStartTrimmedStreamsVector(builder, trimmedStreamsLength)
		for j := trimmedStreamsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(trimmedStreamsOffsets[j])
		}
		trimmedStreamsOffset = builder.EndVector(trimmedStreamsLength)
	}
	TrimStreamsRequestStart(builder)
	TrimStreamsRequestAddTimeoutMs(builder, t.TimeoutMs)
	TrimStreamsRequestAddTrimmedStreams(builder, trimmedStreamsOffset)
	return TrimStreamsRequestEnd(builder)
}

func (rcv *TrimStreamsRequest) UnPackTo(t *TrimStreamsRequestT) {
	t.TimeoutMs = rcv.TimeoutMs()
	trimmedStreamsLength := rcv.TrimmedStreamsLength()
	t.TrimmedStreams = make([]*TrimmedStreamT, trimmedStreamsLength)
	for j := 0; j < trimmedStreamsLength; j++ {
		x := TrimmedStream{}
		rcv.TrimmedStreams(&x, j)
		t.TrimmedStreams[j] = x.UnPack()
	}
}

func (rcv *TrimStreamsRequest) UnPack() *TrimStreamsRequestT {
	if rcv == nil { return nil }
	t := &TrimStreamsRequestT{}
	rcv.UnPackTo(t)
	return t
}

type TrimStreamsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTrimStreamsRequest(buf []byte, offset flatbuffers.UOffsetT) *TrimStreamsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrimStreamsRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTrimStreamsRequest(buf []byte, offset flatbuffers.UOffsetT) *TrimStreamsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrimStreamsRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TrimStreamsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrimStreamsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TrimStreamsRequest) TimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TrimStreamsRequest) MutateTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TrimStreamsRequest) TrimmedStreams(obj *TrimmedStream, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TrimStreamsRequest) TrimmedStreamsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TrimStreamsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TrimStreamsRequestAddTimeoutMs(builder *flatbuffers.Builder, timeoutMs int32) {
	builder.PrependInt32Slot(0, timeoutMs, 0)
}
func TrimStreamsRequestAddTrimmedStreams(builder *flatbuffers.Builder, trimmedStreams flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(trimmedStreams), 0)
}
func TrimStreamsRequestStartTrimmedStreamsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TrimStreamsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
