// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpcfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UpdateStreamResultT struct {
	Stream *StreamT `json:"stream"`
	ErrorCode ErrorCode `json:"error_code"`
	ErrorMessage string `json:"error_message"`
}

func (t *UpdateStreamResultT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	streamOffset := t.Stream.Pack(builder)
	errorMessageOffset := flatbuffers.UOffsetT(0)
	if t.ErrorMessage != "" {
		errorMessageOffset = builder.CreateString(t.ErrorMessage)
	}
	UpdateStreamResultStart(builder)
	UpdateStreamResultAddStream(builder, streamOffset)
	UpdateStreamResultAddErrorCode(builder, t.ErrorCode)
	UpdateStreamResultAddErrorMessage(builder, errorMessageOffset)
	return UpdateStreamResultEnd(builder)
}

func (rcv *UpdateStreamResult) UnPackTo(t *UpdateStreamResultT) {
	t.Stream = rcv.Stream(nil).UnPack()
	t.ErrorCode = rcv.ErrorCode()
	t.ErrorMessage = string(rcv.ErrorMessage())
}

func (rcv *UpdateStreamResult) UnPack() *UpdateStreamResultT {
	if rcv == nil { return nil }
	t := &UpdateStreamResultT{}
	rcv.UnPackTo(t)
	return t
}

type UpdateStreamResult struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateStreamResult(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateStreamResult{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUpdateStreamResult(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateStreamResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UpdateStreamResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateStreamResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateStreamResult) Stream(obj *Stream) *Stream {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Stream)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *UpdateStreamResult) ErrorCode() ErrorCode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ErrorCode(rcv._tab.GetInt16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *UpdateStreamResult) MutateErrorCode(n ErrorCode) bool {
	return rcv._tab.MutateInt16Slot(6, int16(n))
}

func (rcv *UpdateStreamResult) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UpdateStreamResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UpdateStreamResultAddStream(builder *flatbuffers.Builder, stream flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(stream), 0)
}
func UpdateStreamResultAddErrorCode(builder *flatbuffers.Builder, errorCode ErrorCode) {
	builder.PrependInt16Slot(1, int16(errorCode), 0)
}
func UpdateStreamResultAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(errorMessage), 0)
}
func UpdateStreamResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
